version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
