packages:
  - "sdk"
  - "packages/**"
  - "examples/**"
  - "test"
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@openfort/shield-js"
  - "@isaacs/brace-expansion"
  - "@openfort/openfort-node"
