/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AbiType
 */
export interface AbiType {
    /**
     * 
     * @type {string}
     * @memberof AbiType
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AbiType
     */
    'type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AbiType
     */
    'indexed'?: boolean;
    /**
     * 
     * @type {any}
     * @memberof AbiType
     */
    'internalType'?: any;
    /**
     * 
     * @type {Array<AbiType>}
     * @memberof AbiType
     */
    'components'?: Array<AbiType>;
}

