/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AbiType } from './abi-type';

/**
 * 
 * @export
 * @interface Abi
 */
export interface Abi {
    /**
     * 
     * @type {string}
     * @memberof Abi
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abi
     */
    'type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Abi
     */
    'anonymous'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Abi
     */
    'payable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Abi
     */
    'constant'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Abi
     */
    'stateMutability'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abi
     */
    'gas'?: string;
    /**
     * 
     * @type {Array<AbiType>}
     * @memberof Abi
     */
    'inputs'?: Array<AbiType>;
    /**
     * 
     * @type {Array<AbiType>}
     * @memberof Abi
     */
    'outputs'?: Array<AbiType>;
}

