/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountInfoPost200ResponseUser } from './account-info-post200-response-user';

/**
 * 
 * @export
 * @interface AccountInfoPost200Response
 */
export interface AccountInfoPost200Response {
    /**
     * 
     * @type {AccountInfoPost200ResponseUser}
     * @memberof AccountInfoPost200Response
     */
    'user': AccountInfoPost200ResponseUser;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AccountInfoPost200Response
     */
    'data': { [key: string]: any; };
}

