/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { UserOperationV8 } from './user-operation-v8';

/**
 * 
 * @export
 * @interface AccountAbstractionV8Details
 */
export interface AccountAbstractionV8Details {
    /**
     * 
     * @type {UserOperationV8}
     * @memberof AccountAbstractionV8Details
     */
    'userOperation': UserOperationV8;
    /**
     * A User Operation hash.
     * @type {string}
     * @memberof AccountAbstractionV8Details
     */
    'userOperationHash': string;
}

