/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SortOrder } from './sort-order';

/**
 * 
 * @export
 * @interface AccountListQueriesV2
 */
export interface AccountListQueriesV2 {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'skip'?: number;
    /**
     * 
     * @type {SortOrder}
     * @memberof AccountListQueriesV2
     */
    'order'?: SortOrder;
    /**
     * The chain ID. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'chainId'?: number;
    /**
     * Specifies the unique user ID (starts with pla_)
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'user'?: string;
    /**
     * Specifies the type of chain
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'chainType'?: string;
    /**
     * Specifies the type of account
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'accountType'?: string;
    /**
     * Specifies the account address
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'address'?: string;
}



