/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SmartAccountData } from './smart-account-data';

/**
 * 
 * @export
 * @interface AccountV2Response
 */
export interface AccountV2Response {
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'user': string;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'accountType': string;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'ownerAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'chainType': string;
    /**
     * 
     * @type {number}
     * @memberof AccountV2Response
     */
    'chainId'?: number;
    /**
     * 
     * @type {number}
     * @memberof AccountV2Response
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof AccountV2Response
     */
    'updatedAt': number;
    /**
     * 
     * @type {SmartAccountData}
     * @memberof AccountV2Response
     */
    'smartAccount'?: SmartAccountData;
    /**
     * 
     * @type {string}
     * @memberof AccountV2Response
     */
    'recoveryMethod'?: string;
}

