/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePOLICYRULE } from './entity-type-policyrule';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyRuleTypeACCOUNT } from './policy-rule-type-account';

/**
 * 
 * @export
 * @interface AccountPolicyRuleResponse
 */
export interface AccountPolicyRuleResponse {
    /**
     * 
     * @type {string}
     * @memberof AccountPolicyRuleResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePOLICYRULE}
     * @memberof AccountPolicyRuleResponse
     */
    'object': EntityTypePOLICYRULE;
    /**
     * 
     * @type {number}
     * @memberof AccountPolicyRuleResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {PolicyRuleTypeACCOUNT}
     * @memberof AccountPolicyRuleResponse
     */
    'type': PolicyRuleTypeACCOUNT;
}



