/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrismaSortOrder } from './prisma-sort-order';

/**
 * 
 * @export
 * @interface AccountListQueriesV2
 */
export interface AccountListQueriesV2 {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'skip'?: number;
    /**
     * 
     * @type {PrismaSortOrder}
     * @memberof AccountListQueriesV2
     */
    'order'?: PrismaSortOrder;
    /**
     * The chain ID. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof AccountListQueriesV2
     */
    'chainId'?: number;
    /**
     * Specifies the unique user ID (starts with pla_)
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'user'?: string;
    /**
     * The chain type. Must be either \"EVM\" or \"SVM\".
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'chainType'?: AccountListQueriesV2ChainTypeEnum;
    /**
     * Specifies the type of account. Must be either \"Smart Account\" or \"Externally Owned Account\".
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'accountType'?: AccountListQueriesV2AccountTypeEnum;
    /**
     * Specifies the account address
     * @type {string}
     * @memberof AccountListQueriesV2
     */
    'address'?: string;
}

export const AccountListQueriesV2ChainTypeEnum = {
    Evm: 'EVM',
    Svm: 'SVM'
} as const;

export type AccountListQueriesV2ChainTypeEnum = typeof AccountListQueriesV2ChainTypeEnum[keyof typeof AccountListQueriesV2ChainTypeEnum];
export const AccountListQueriesV2AccountTypeEnum = {
    ExternallyOwnedAccount: 'Externally Owned Account',
    SmartAccount: 'Smart Account',
    DelegatedAccount: 'Delegated Account'
} as const;

export type AccountListQueriesV2AccountTypeEnum = typeof AccountListQueriesV2AccountTypeEnum[keyof typeof AccountListQueriesV2AccountTypeEnum];


