/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const ApiKeyType = {
    PUBLIC_KEY: 'pk',
    SECRET_KEY: 'sk',
    PUBLIC_KEY_SHIELD: 'pk_shield',
    SECRET_KEY_SHIELD: 'sk_shield',
    BACKEND_WALLET_PUBLIC_KEY: 'pk_wallet'
} as const;

export type ApiKeyType = typeof ApiKeyType[keyof typeof ApiKeyType];



