/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { LinkedAccountResponseV2 } from './linked-account-response-v2';

/**
 * 
 * @export
 * @interface AuthUserResponse
 */
export interface AuthUserResponse {
    /**
     * 
     * @type {string}
     * @memberof AuthUserResponse
     */
    'id': string;
    /**
     * 
     * @type {number}
     * @memberof AuthUserResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {string}
     * @memberof AuthUserResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserResponse
     */
    'walletId': string;
    /**
     * 
     * @type {string}
     * @memberof AuthUserResponse
     */
    'email': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthUserResponse
     */
    'emailVerified': boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthUserResponse
     */
    'phoneNumber': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthUserResponse
     */
    'phoneNumberVerified': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthUserResponse
     */
    'isAnonymous'?: boolean;
    /**
     * 
     * @type {Array<LinkedAccountResponseV2>}
     * @memberof AuthUserResponse
     */
    'linkedAccounts': Array<LinkedAccountResponseV2>;
}

