/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Enum of the supporting OAuth providers.
 * @export
 * @enum {string}
 */

export const AuthProvider = {
    Email: 'email',
    Accelbyte: 'accelbyte',
    Firebase: 'firebase',
    Google: 'google',
    Lootlocker: 'lootlocker',
    Playfab: 'playfab',
    Wallet: 'wallet'
} as const;

export type AuthProvider = typeof AuthProvider[keyof typeof AuthProvider];



