/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BackendWalletResponse } from './backend-wallet-response';

/**
 * List of backend wallets response.
 * @export
 * @interface BackendWalletListResponse
 */
export interface BackendWalletListResponse {
    /**
     * The type of object.
     * @type {string}
     * @memberof BackendWalletListResponse
     */
    'object': BackendWalletListResponseObjectEnum;
    /**
     * API endpoint URL.
     * @type {string}
     * @memberof BackendWalletListResponse
     */
    'url': string;
    /**
     * List of backend wallets.
     * @type {Array<BackendWalletResponse>}
     * @memberof BackendWalletListResponse
     */
    'data': Array<BackendWalletResponse>;
    /**
     * Starting index.
     * @type {number}
     * @memberof BackendWalletListResponse
     */
    'start': number;
    /**
     * Ending index.
     * @type {number}
     * @memberof BackendWalletListResponse
     */
    'end': number;
    /**
     * Total number of wallets.
     * @type {number}
     * @memberof BackendWalletListResponse
     */
    'total': number;
}

export const BackendWalletListResponseObjectEnum = {
    List: 'list'
} as const;

export type BackendWalletListResponseObjectEnum = typeof BackendWalletListResponseObjectEnum[keyof typeof BackendWalletListResponseObjectEnum];


