/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Query parameters for listing backend wallets.
 * @export
 * @interface BackendWalletListQueries
 */
export interface BackendWalletListQueries {
    /**
     * Number of wallets to return (default: 10, max: 100).
     * @type {number}
     * @memberof BackendWalletListQueries
     */
    'limit'?: number;
    /**
     * Number of wallets to skip (for pagination).
     * @type {number}
     * @memberof BackendWalletListQueries
     */
    'skip'?: number;
    /**
     * Filter by chain type.
     * @type {string}
     * @memberof BackendWalletListQueries
     */
    'chainType'?: BackendWalletListQueriesChainTypeEnum;
    /**
     * Filter by wallet address.
     * @type {string}
     * @memberof BackendWalletListQueries
     */
    'address'?: string;
    /**
     * Filter by wallet name.
     * @type {string}
     * @memberof BackendWalletListQueries
     */
    'name'?: string;
    /**
     * Filter by associated wallet ID (starts with `pla_`).
     * @type {string}
     * @memberof BackendWalletListQueries
     */
    'wallet'?: string;
}

export const BackendWalletListQueriesChainTypeEnum = {
    Evm: 'EVM',
    Svm: 'SVM'
} as const;

export type BackendWalletListQueriesChainTypeEnum = typeof BackendWalletListQueriesChainTypeEnum[keyof typeof BackendWalletListQueriesChainTypeEnum];


