/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { APITopicBALANCEPROJECT } from './apitopic-balanceproject';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypeEVENT } from './entity-type-event';

/**
 * 
 * @export
 * @interface BalanceEventResponse
 */
export interface BalanceEventResponse {
    /**
     * 
     * @type {string}
     * @memberof BalanceEventResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypeEVENT}
     * @memberof BalanceEventResponse
     */
    'object': EntityTypeEVENT;
    /**
     * 
     * @type {number}
     * @memberof BalanceEventResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {APITopicBALANCEPROJECT}
     * @memberof BalanceEventResponse
     */
    'topic': APITopicBALANCEPROJECT;
    /**
     * 
     * @type {string}
     * @memberof BalanceEventResponse
     */
    'threshold': string;
}



