/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EmailSampleResponse } from './email-sample-response';
// May contain unused imports in some cases
// @ts-ignore
import { ResponseTypeLIST } from './response-type-list';

/**
 * 
 * @export
 * @interface BaseEntityListResponseEmailSampleResponse
 */
export interface BaseEntityListResponseEmailSampleResponse {
    /**
     * 
     * @type {ResponseTypeLIST}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'object': ResponseTypeLIST;
    /**
     * 
     * @type {string}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'url': string;
    /**
     * 
     * @type {Array<EmailSampleResponse>}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'data': Array<EmailSampleResponse>;
    /**
     * 
     * @type {number}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'start': number;
    /**
     * 
     * @type {number}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'end': number;
    /**
     * 
     * @type {number}
     * @memberof BaseEntityListResponseEmailSampleResponse
     */
    'total': number;
}



