/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single call executed by the transaction. Either a raw call (`to`/`value`/`data`) or a contract call resolved through a registered contract (`contractId`/`functionName`/`functionArgs`).
 * @export
 * @interface Call
 */
export interface Call {
    /**
     * The address that receives the call. Use *only* for raw calls and native token transfers; a `pla_...` or `acc_...` id is converted to the corresponding address.
     * @type {string}
     * @memberof Call
     */
    'to'?: string;
    /**
     * The value sent with the call, as a stringified number in WEI (factor 10^18).
     * @type {string}
     * @memberof Call
     */
    'value'?: string;
    /**
     * Raw calldata (hex) for the call. Use instead of `contractId`/`functionName`.
     * @type {string}
     * @memberof Call
     */
    'data'?: string;
    /**
     * Hex data appended to the encoded function call.
     * @type {string}
     * @memberof Call
     */
    'dataSuffix'?: string;
    /**
     * ID of the contract the call interacts with. Must have been added to Openfort first, starts with `con_`.
     * @type {string}
     * @memberof Call
     */
    'contractId'?: string;
    /**
     * The function name of the contract. Accepts a function signature as well (e.g. mint(address)).
     * @type {string}
     * @memberof Call
     */
    'functionName'?: string;
    /**
     * The function arguments of the contract, formatted as strings.
     * @type {Array<any>}
     * @memberof Call
     */
    'functionArgs'?: Array<any>;
}

