/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { SponsorSchemaCHARGECUSTOMTOKENS } from './sponsor-schema-chargecustomtokens';

/**
 * 
 * @export
 * @interface ChargeCustomTokenPolicyStrategy
 */
export interface ChargeCustomTokenPolicyStrategy {
    /**
     * 
     * @type {SponsorSchemaCHARGECUSTOMTOKENS}
     * @memberof ChargeCustomTokenPolicyStrategy
     */
    'sponsorSchema': SponsorSchemaCHARGECUSTOMTOKENS;
    /**
     * 
     * @type {string}
     * @memberof ChargeCustomTokenPolicyStrategy
     */
    'depositor'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ChargeCustomTokenPolicyStrategy
     */
    'tokenContract': string;
    /**
     * 
     * @type {string}
     * @memberof ChargeCustomTokenPolicyStrategy
     */
    'tokenContractAmount': string;
}



