/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckVerificationOtpRequest
 */
export interface CheckVerificationOtpRequest {
    /**
     * Email address the OTP was sent to
     * @type {string}
     * @memberof CheckVerificationOtpRequest
     */
    'email': string;
    /**
     * Type of the OTP
     * @type {string}
     * @memberof CheckVerificationOtpRequest
     */
    'type': CheckVerificationOtpRequestTypeEnum;
    /**
     * OTP to verify
     * @type {string}
     * @memberof CheckVerificationOtpRequest
     */
    'otp': string;
}

export const CheckVerificationOtpRequestTypeEnum = {
    EmailVerification: 'email-verification',
    SignIn: 'sign-in',
    ForgetPassword: 'forget-password'
} as const;

export type CheckVerificationOtpRequestTypeEnum = typeof CheckVerificationOtpRequestTypeEnum[keyof typeof CheckVerificationOtpRequestTypeEnum];


