/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CodeChallenge
 */
export interface CodeChallenge {
    /**
     * The code challenge.
     * @type {string}
     * @memberof CodeChallenge
     */
    'codeChallenge': string;
    /**
     * The code verifier.
     * @type {string}
     * @memberof CodeChallenge
     */
    'method': CodeChallengeMethodEnum;
}

export const CodeChallengeMethodEnum = {
    Plain: 'plain',
    S256: 'S256'
} as const;

export type CodeChallengeMethodEnum = typeof CodeChallengeMethodEnum[keyof typeof CodeChallengeMethodEnum];


