/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CompleteRecoveryRequest
 */
export interface CompleteRecoveryRequest {
    /**
     * Address of the new owner
     * @type {string}
     * @memberof CompleteRecoveryRequest
     */
    'newOwnerAddress': string;
    /**
     * Signatures by the guardians
     * @type {Array<string>}
     * @memberof CompleteRecoveryRequest
     */
    'signatures'?: Array<string>;
    /**
     * The policy ID (starts with pol_)
     * @type {string}
     * @memberof CompleteRecoveryRequest
     */
    'policy': string;
}

