/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrismaSortOrder } from './prisma-sort-order';

/**
 * 
 * @export
 * @interface ContractListQueries
 */
export interface ContractListQueries {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof ContractListQueries
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof ContractListQueries
     */
    'skip'?: number;
    /**
     * 
     * @type {PrismaSortOrder}
     * @memberof ContractListQueries
     */
    'order'?: PrismaSortOrder;
    /**
     * Specifies the name of the contract.
     * @type {string}
     * @memberof ContractListQueries
     */
    'name'?: string;
    /**
     * Specifies whether to include deleted contracts.
     * @type {boolean}
     * @memberof ContractListQueries
     */
    'deleted'?: boolean;
    /**
     * The chain ID of the contract.
     * @type {number}
     * @memberof ContractListQueries
     */
    'chainId'?: number;
    /**
     * Specifies the address of the contract.
     * @type {string}
     * @memberof ContractListQueries
     */
    'address'?: string;
}



