/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { APITopicBALANCECONTRACT } from './apitopic-balancecontract';
// May contain unused imports in some cases
// @ts-ignore
import { EntityIdResponse } from './entity-id-response';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypeEVENT } from './entity-type-event';

/**
 * 
 * @export
 * @interface ContractEventResponse
 */
export interface ContractEventResponse {
    /**
     * 
     * @type {string}
     * @memberof ContractEventResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypeEVENT}
     * @memberof ContractEventResponse
     */
    'object': EntityTypeEVENT;
    /**
     * 
     * @type {number}
     * @memberof ContractEventResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {APITopicBALANCECONTRACT}
     * @memberof ContractEventResponse
     */
    'topic': APITopicBALANCECONTRACT;
    /**
     * 
     * @type {string}
     * @memberof ContractEventResponse
     */
    'threshold': string;
    /**
     * 
     * @type {EntityIdResponse}
     * @memberof ContractEventResponse
     */
    'contract': EntityIdResponse;
    /**
     * 
     * @type {string}
     * @memberof ContractEventResponse
     */
    'functionName': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ContractEventResponse
     */
    'functionArgs': Array<string>;
}



