/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Interaction } from './interaction';

/**
 * 
 * @export
 * @interface CreateTransactionRequestV2
 */
export interface CreateTransactionRequestV2 {
    /**
     * The chain ID. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof CreateTransactionRequestV2
     */
    'chainId': number;
    /**
     * ID of the account that executes the transaction (starts with `acc_`).
     * @type {string}
     * @memberof CreateTransactionRequestV2
     */
    'account': string;
    /**
     * ID of the fee sponsorship that pays for gas (starts with `pol_`). Omit to pay gas from the account\'s native token balance.
     * @type {string}
     * @memberof CreateTransactionRequestV2
     */
    'feeSponsorship'?: string;
    /**
     * For a fee sponsorship that accepts several user-pay ERC-20 tokens, the on-chain address of the token the user pays the fee in. Must be one of the sponsorship\'s configured tokens on this chain.
     * @type {string}
     * @memberof CreateTransactionRequestV2
     */
    'feeSponsorshipToken'?: string;
    /**
     * 
     * @type {Array<Interaction>}
     * @memberof CreateTransactionRequestV2
     */
    'calls': Array<Interaction>;
    /**
     * Whether to hold the request until the transaction is mined and the `receipt` is available (default `true`). Set to `false` to respond as soon as the transaction is broadcast (`status: \"submitted\"`) and poll `GET /v2/transactions/{id}` for the outcome.
     * @type {boolean}
     * @memberof CreateTransactionRequestV2
     */
    'waitForReceipt'?: boolean;
    /**
     * EIP-7702 signed authorization (hex) for a delegated account that is not yet delegated on-chain.
     * @type {string}
     * @memberof CreateTransactionRequestV2
     */
    'authorization'?: string;
}

