/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { APITopic } from './apitopic';

/**
 * 
 * @export
 * @interface CreateEventRequest
 */
export interface CreateEventRequest {
    /**
     * Specifies the name of the event
     * @type {string}
     * @memberof CreateEventRequest
     */
    'name': string;
    /**
     * 
     * @type {APITopic}
     * @memberof CreateEventRequest
     */
    'topic': APITopic;
    /**
     * Specifies the contract id (if the event is a contract event)
     * @type {string}
     * @memberof CreateEventRequest
     */
    'contract'?: string;
    /**
     * Specifies the function arguments (if the event is a contract event)
     * @type {Array<string>}
     * @memberof CreateEventRequest
     */
    'functionArgs'?: Array<string>;
    /**
     * Specifies the function name (if the event is a contract event)
     * @type {string}
     * @memberof CreateEventRequest
     */
    'functionName'?: string;
    /**
     * Specifies the developer account id (if the event is a developer account event)
     * @type {string}
     * @memberof CreateEventRequest
     */
    'developerAccount'?: string;
    /**
     * Specifies the chain id (if the event is a developer account event)
     * @type {number}
     * @memberof CreateEventRequest
     */
    'chainId'?: number;
    /**
     * Threshold for the event (if the event is a contract, dev account or project event)
     * @type {string}
     * @memberof CreateEventRequest
     */
    'threshold'?: string;
    /**
     * Specifies the number of confirmations required for the event to trigger
     * @type {number}
     * @memberof CreateEventRequest
     */
    'numberOfBlocks'?: number;
}



