/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FundingSourceRequest } from './funding-source-request';

/**
 * A self-custody crypto payment method (source) for a session.
 * @export
 * @interface CryptoPaymentMethodRequest
 */
export interface CryptoPaymentMethodRequest {
    /**
     * Self-custody source family.
     * @type {string}
     * @memberof CryptoPaymentMethodRequest
     */
    'type': CryptoPaymentMethodRequestTypeEnum;
    /**
     * 
     * @type {FundingSourceRequest}
     * @memberof CryptoPaymentMethodRequest
     */
    'source': FundingSourceRequest;
    /**
     * Origin-chain address refunded if the deposit bounces. Defaults to the target address (valid for same-address EVM embedded wallets).
     * @type {string}
     * @memberof CryptoPaymentMethodRequest
     */
    'refundTo'?: string;
}

export const CryptoPaymentMethodRequestTypeEnum = {
    Evm: 'evm',
    Solana: 'solana'
} as const;

export type CryptoPaymentMethodRequestTypeEnum = typeof CryptoPaymentMethodRequestTypeEnum[keyof typeof CryptoPaymentMethodRequestTypeEnum];


