/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteUserPostRequest
 */
export interface DeleteUserPostRequest {
    /**
     * The callback URL to redirect to after the user is deleted
     * @type {string}
     * @memberof DeleteUserPostRequest
     */
    'callbackURL'?: string | null;
    /**
     * The password of the user is required to delete the user
     * @type {string}
     * @memberof DeleteUserPostRequest
     */
    'password'?: string | null;
    /**
     * The token to delete the user is required
     * @type {string}
     * @memberof DeleteUserPostRequest
     */
    'token'?: string | null;
}

