/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DeleteProjectRequest
 */
export interface DeleteProjectRequest {
    /**
     * The exact name of the project, typed as confirmation. Deletion is irreversible: it wipes all project data across every Openfort service, including embedded-wallet key material.
     * @type {string}
     * @memberof DeleteProjectRequest
     */
    'confirmation': string;
}

