/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DeveloperAccountResponseExpandable } from './developer-account-response-expandable';
// May contain unused imports in some cases
// @ts-ignore
import { SortOrder } from './sort-order';

/**
 * 
 * @export
 * @interface DeveloperAccountListQueries
 */
export interface DeveloperAccountListQueries {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof DeveloperAccountListQueries
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof DeveloperAccountListQueries
     */
    'skip'?: number;
    /**
     * 
     * @type {SortOrder}
     * @memberof DeveloperAccountListQueries
     */
    'order'?: SortOrder;
    /**
     * Specifies the fields to expand in the response.
     * @type {Array<DeveloperAccountResponseExpandable>}
     * @memberof DeveloperAccountListQueries
     */
    'expand'?: Array<DeveloperAccountResponseExpandable>;
    /**
     * Specifies whether to include deleted dev accounts.
     * @type {boolean}
     * @memberof DeveloperAccountListQueries
     */
    'deleted'?: boolean;
}



