/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 
 * @export
 * @interface EmailOtpVerifyEmailPost200Response
 */
export interface EmailOtpVerifyEmailPost200Response {
    /**
     * Indicates if the verification was successful
     * @type {boolean}
     * @memberof EmailOtpVerifyEmailPost200Response
     */
    'status': boolean;
    /**
     * Session token if autoSignInAfterVerification is enabled, otherwise null
     * @type {string}
     * @memberof EmailOtpVerifyEmailPost200Response
     */
    'token': string | null;
    /**
     * 
     * @type {User}
     * @memberof EmailOtpVerifyEmailPost200Response
     */
    'user': User;
}

