/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EmailOtpCheckVerificationOtpPostRequest
 */
export interface EmailOtpCheckVerificationOtpPostRequest {
    /**
     * Email address the OTP was sent to
     * @type {string}
     * @memberof EmailOtpCheckVerificationOtpPostRequest
     */
    'email': string;
    /**
     * Type of the OTP
     * @type {string}
     * @memberof EmailOtpCheckVerificationOtpPostRequest
     */
    'type': string;
    /**
     * OTP to verify
     * @type {string}
     * @memberof EmailOtpCheckVerificationOtpPostRequest
     */
    'otp': string;
}

