/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EvaluatePolicyV2Payload } from './evaluate-policy-v2-payload';

/**
 * 
 * @export
 * @interface EvaluatePolicyV2Request
 */
export interface EvaluatePolicyV2Request {
    /**
     * The signing operation to evaluate. EVM: signEvmTransaction, sendEvmTransaction, signEvmTypedData, signEvmMessage, signEvmHash Solana: signSolTransaction, sendSolTransaction, signSolMessage
     * @type {string}
     * @memberof EvaluatePolicyV2Request
     */
    'operation': string;
    /**
     * The account ID to evaluate policies for (starts with acc_). If not provided, only project-scoped policies are evaluated.
     * @type {string}
     * @memberof EvaluatePolicyV2Request
     */
    'accountId'?: string;
    /**
     * 
     * @type {EvaluatePolicyV2Payload}
     * @memberof EvaluatePolicyV2Request
     */
    'payload'?: EvaluatePolicyV2Payload;
}

