/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const EvmCriteriaType = {
    EVM_ADDRESS: 'evmAddress',
    ETH_VALUE: 'ethValue',
    EVM_NETWORK: 'evmNetwork',
    EVM_MESSAGE: 'evmMessage',
    EVM_DATA: 'evmData',
    EVM_TYPED_DATA_VERIFYING_CONTRACT: 'evmTypedDataVerifyingContract',
    EVM_TYPED_DATA_FIELD: 'evmTypedDataField',
    NET_USD_CHANGE: 'netUSDChange'
} as const;

export type EvmCriteriaType = typeof EvmCriteriaType[keyof typeof EvmCriteriaType];



