/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RecoveryMethodDetails } from './recovery-method-details';
// May contain unused imports in some cases
// @ts-ignore
import { SmartAccountData } from './smart-account-data';

/**
 * 
 * @export
 * @interface ExportShareResponse
 */
export interface ExportShareResponse {
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'wallet': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'accountType': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'ownerAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'chainType': string;
    /**
     * 
     * @type {number}
     * @memberof ExportShareResponse
     */
    'chainId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExportShareResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof ExportShareResponse
     */
    'updatedAt': number;
    /**
     * 
     * @type {SmartAccountData}
     * @memberof ExportShareResponse
     */
    'smartAccount'?: SmartAccountData;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'recoveryMethod'?: string;
    /**
     * 
     * @type {RecoveryMethodDetails}
     * @memberof ExportShareResponse
     */
    'recoveryMethodDetails'?: RecoveryMethodDetails;
    /**
     * Indicates key custody: \"Developer\" for TEE managed keys, \"User\" for user-managed keys.
     * @type {string}
     * @memberof ExportShareResponse
     */
    'custody': ExportShareResponseCustodyEnum;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'share': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'signerId': string;
    /**
     * 
     * @type {string}
     * @memberof ExportShareResponse
     */
    'userId'?: string;
}

export const ExportShareResponseCustodyEnum = {
    Developer: 'Developer',
    User: 'User'
} as const;

export type ExportShareResponseCustodyEnum = typeof ExportShareResponseCustodyEnum[keyof typeof ExportShareResponseCustodyEnum];


