/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FundingFeeResponse } from './funding-fee-response';
// May contain unused imports in some cases
// @ts-ignore
import { FundingSourceResponse } from './funding-source-response';
// May contain unused imports in some cases
// @ts-ignore
import { FundingWalletDeeplinkResponse } from './funding-wallet-deeplink-response';

/**
 * The resolved payment method — what the client renders.
 * @export
 * @interface FundingPaymentMethodResponse
 */
export interface FundingPaymentMethodResponse {
    /**
     * Source family (\"evm\" or \"solana\").
     * @type {string}
     * @memberof FundingPaymentMethodResponse
     */
    'type': string;
    /**
     * 
     * @type {FundingSourceResponse}
     * @memberof FundingPaymentMethodResponse
     */
    'source': FundingSourceResponse;
    /**
     * Address the user sends the source funds to.
     * @type {string}
     * @memberof FundingPaymentMethodResponse
     */
    'receiverAddress': string;
    /**
     * BIP-21 / EIP-681 / Solana Pay URI for QR rendering.
     * @type {string}
     * @memberof FundingPaymentMethodResponse
     */
    'addressUri': string;
    /**
     * Wallet deeplinks for the transfer, populated client-side.
     * @type {Array<FundingWalletDeeplinkResponse>}
     * @memberof FundingPaymentMethodResponse
     */
    'deeplinks': Array<FundingWalletDeeplinkResponse>;
    /**
     * 
     * @type {Array<FundingFeeResponse>}
     * @memberof FundingPaymentMethodResponse
     */
    'fees': Array<FundingFeeResponse>;
    /**
     * Minimum the user must send for this route (source base units), or null.
     * @type {string}
     * @memberof FundingPaymentMethodResponse
     */
    'minAmount': string | null;
}

