/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A single fee line reported by the rail provider.
 * @export
 * @interface FundingFeeResponse
 */
export interface FundingFeeResponse {
    /**
     * 
     * @type {string}
     * @memberof FundingFeeResponse
     */
    'kind': string;
    /**
     * 
     * @type {string}
     * @memberof FundingFeeResponse
     */
    'amount': string;
    /**
     * 
     * @type {string}
     * @memberof FundingFeeResponse
     */
    'currency': string;
}

