/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Coinbase CDP creds for native wallet pay. Send `privateKey` to set/rotate it.
 * @export
 * @interface FundingConfigCoinbaseRequest
 */
export interface FundingConfigCoinbaseRequest {
    /**
     * 
     * @type {string}
     * @memberof FundingConfigCoinbaseRequest
     */
    'projectId': string;
    /**
     * 
     * @type {string}
     * @memberof FundingConfigCoinbaseRequest
     */
    'keyId': string;
    /**
     * Omit or send empty to keep the existing stored key (write-only secret).
     * @type {string}
     * @memberof FundingConfigCoinbaseRequest
     */
    'privateKey'?: string;
}

