/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GET/PUT /v2/funding/config response — the project funding config with the credentials replaced by presence flags. Stored secrets are write-only: the dashboard renders \"configured / not configured\", never a value it could echo back.
 * @export
 * @interface FundingConfigResponse
 */
export interface FundingConfigResponse {
    /**
     * 
     * @type {string}
     * @memberof FundingConfigResponse
     */
    'ecosystem': string;
    /**
     * 
     * @type {string}
     * @memberof FundingConfigResponse
     */
    'defaultChain': string;
    /**
     * 
     * @type {string}
     * @memberof FundingConfigResponse
     */
    'defaultCurrency': string;
    /**
     * 
     * @type {string}
     * @memberof FundingConfigResponse
     */
    'recommendedAmount': string;
    /**
     * 
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'crossChainBridging': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'onrampEnabled': boolean;
    /**
     * Enabled web2 methods (FundingMethod values), in display order.
     * @type {Array<string>}
     * @memberof FundingConfigResponse
     */
    'onrampMethods': Array<string>;
    /**
     * Whether native wallet pay (Apple/Google Pay) is offered. Needs the project\'s own CDP keys.
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'walletPayEnabled': boolean;
    /**
     * Whether Stripe\'s in-page (embedded) rail is offered. Needs the project\'s own Link OAuth client.
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'stripeEnabled': boolean;
    /**
     * Whether hosted-checkout popup rows (including the rest-of-world fallback) are offered.
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'hostedCheckoutEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'depositAddressEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'depositFromWalletEnabled': boolean;
    /**
     * The project\'s Stripe publishable key, handed to the client so the embedded component can initialize. Public by design — it belongs to the same Stripe account as the embedded credentials below, so it is per-project too.
     * @type {string}
     * @memberof FundingConfigResponse
     */
    'stripePublishableKey': string;
    /**
     * The project\'s CDP key pair is set (webhook secret is separate and optional).
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'coinbaseHeadlessConfigured': boolean;
    /**
     * The project\'s Stripe secret key and Link OAuth client are set (webhook secret is separate and optional).
     * @type {boolean}
     * @memberof FundingConfigResponse
     */
    'stripeEmbeddedConfigured': boolean;
}

