/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Where the funded crypto should land.
 * @export
 * @interface FundingTargetRequest
 */
export interface FundingTargetRequest {
    /**
     * Destination CAIP-2 chain id.
     * @type {string}
     * @memberof FundingTargetRequest
     */
    'chain': string;
    /**
     * Destination token contract, or the zero address for the chain\'s native asset.
     * @type {string}
     * @memberof FundingTargetRequest
     */
    'currency': string;
    /**
     * Destination wallet that receives the bridged funds.
     * @type {string}
     * @memberof FundingTargetRequest
     */
    'address': string;
}

