/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FundingChainCurrencyResponse } from './funding-chain-currency-response';

/**
 * A source chain the funding rail can route a deposit from.
 * @export
 * @interface FundingChainResponse
 */
export interface FundingChainResponse {
    /**
     * CAIP-2 chain id, e.g. \"eip155:8453\".
     * @type {string}
     * @memberof FundingChainResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FundingChainResponse
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof FundingChainResponse
     */
    'logo': string | null;
    /**
     * \"evm\" | \"svm\".
     * @type {string}
     * @memberof FundingChainResponse
     */
    'vmType': string;
    /**
     * 
     * @type {Array<FundingChainCurrencyResponse>}
     * @memberof FundingChainResponse
     */
    'currencies': Array<FundingChainCurrencyResponse>;
}

