/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePOLICYRULE } from './entity-type-policyrule';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyRateLimitGASPERTRANSACTION } from './policy-rate-limit-gaspertransaction';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyRuleTypeRATELIMIT } from './policy-rule-type-ratelimit';

/**
 * 
 * @export
 * @interface GasPerTransactionLimitPolicyRuleResponse
 */
export interface GasPerTransactionLimitPolicyRuleResponse {
    /**
     * 
     * @type {string}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePOLICYRULE}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'object': EntityTypePOLICYRULE;
    /**
     * 
     * @type {number}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {PolicyRuleTypeRATELIMIT}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'type': PolicyRuleTypeRATELIMIT;
    /**
     * 
     * @type {PolicyRateLimitGASPERTRANSACTION}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'functionName': PolicyRateLimitGASPERTRANSACTION;
    /**
     * 
     * @type {string}
     * @memberof GasPerTransactionLimitPolicyRuleResponse
     */
    'gasLimit': string;
}



