/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ErrorTypeINVALIDREQUESTERROR } from './error-type-invalidrequesterror';
// May contain unused imports in some cases
// @ts-ignore
import { FieldErrorsValue } from './field-errors-value';

/**
 * 
 * @export
 * @interface InvalidRequestError
 */
export interface InvalidRequestError {
    /**
     * 
     * @type {ErrorTypeINVALIDREQUESTERROR}
     * @memberof InvalidRequestError
     */
    'type': ErrorTypeINVALIDREQUESTERROR;
    /**
     * 
     * @type {string}
     * @memberof InvalidRequestError
     */
    'message': string;
    /**
     * 
     * @type {{ [key: string]: FieldErrorsValue; }}
     * @memberof InvalidRequestError
     */
    'details'?: { [key: string]: FieldErrorsValue; };
    /**
     * Machine-readable cause, when the thrower disambiguates one (e.g. funding_key_required).
     * @type {string}
     * @memberof InvalidRequestError
     */
    'code'?: string;
    /**
     * Offending request field path, when the thrower points at one (e.g. target.chain).
     * @type {string}
     * @memberof InvalidRequestError
     */
    'param'?: string;
}



