/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthProviderResponseV2 } from './auth-provider-response-v2';

/**
 * 
 * @export
 * @interface LinkedAccountResponseV2
 */
export interface LinkedAccountResponseV2 {
    /**
     * 
     * @type {AuthProviderResponseV2}
     * @memberof LinkedAccountResponseV2
     */
    'provider': AuthProviderResponseV2;
    /**
     * 
     * @type {number}
     * @memberof LinkedAccountResponseV2
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof LinkedAccountResponseV2
     */
    'updatedAt': number;
    /**
     * 
     * @type {string}
     * @memberof LinkedAccountResponseV2
     */
    'accountId'?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkedAccountResponseV2
     */
    'chainType'?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkedAccountResponseV2
     */
    'connectorType'?: string;
    /**
     * 
     * @type {string}
     * @memberof LinkedAccountResponseV2
     */
    'walletClientType'?: string;
}



