/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthMigrationStatus } from './auth-migration-status';
// May contain unused imports in some cases
// @ts-ignore
import { AuthProvider } from './auth-provider';
// May contain unused imports in some cases
// @ts-ignore
import { SortOrder } from './sort-order';

/**
 * Request for listing Migrations
 * @export
 * @interface ListMigrationsRequest
 */
export interface ListMigrationsRequest {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof ListMigrationsRequest
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof ListMigrationsRequest
     */
    'skip'?: number;
    /**
     * 
     * @type {SortOrder}
     * @memberof ListMigrationsRequest
     */
    'order'?: SortOrder;
    /**
     * 
     * @type {AuthProvider}
     * @memberof ListMigrationsRequest
     */
    'sourceProvider'?: AuthProvider;
    /**
     * 
     * @type {AuthProvider}
     * @memberof ListMigrationsRequest
     */
    'destinationProvider'?: AuthProvider;
    /**
     * Status of the migration
     * @type {Array<AuthMigrationStatus>}
     * @memberof ListMigrationsRequest
     */
    'status'?: Array<AuthMigrationStatus>;
}



