/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OAuthProviderLOOTLOCKER } from './oauth-provider-lootlocker';

/**
 * LootLocker oauth configuration
 * @export
 * @interface LootLockerOAuthConfig
 */
export interface LootLockerOAuthConfig {
    /**
     * Enable OAuth provider.
     * @type {boolean}
     * @memberof LootLockerOAuthConfig
     */
    'enabled': boolean;
    /**
     * 
     * @type {OAuthProviderLOOTLOCKER}
     * @memberof LootLockerOAuthConfig
     */
    'provider': OAuthProviderLOOTLOCKER;
}



