/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Mapping strategy for the migration. This is used to transform the ids between the source and destination providers. For the transformation, the order of the operations is: 1. Trim the prefix and suffix from the destination id. 2. Add the prefix and suffix to the destination id. When a user is authenticated in the destination provider, the id is transformed using the mapping strategy to find if exists in the source provider. If the id is not found, the user is created in the destination provider. If the id is found, the user in the destination provider is linked to the source provider.
 * @export
 * @interface MappingStrategy
 */
export interface MappingStrategy {
    /**
     * Prefix to trim from the destination id.
     * @type {string}
     * @memberof MappingStrategy
     */
    'trimPrefix'?: string;
    /**
     * Suffix to trim from the destination id.
     * @type {string}
     * @memberof MappingStrategy
     */
    'trimSuffix'?: string;
    /**
     * Prefix to add to the destination id.
     * @type {string}
     * @memberof MappingStrategy
     */
    'addPrefix'?: string;
    /**
     * Suffix to add to the destination id.
     * @type {string}
     * @memberof MappingStrategy
     */
    'addSuffix'?: string;
}

