/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Mint Address criterion - validates token mint addresses. Operators: \"==\", \"in\"
 * @export
 * @interface MintAddressCriterionRequest
 */
export interface MintAddressCriterionRequest {
    /**
     * The type of criterion.
     * @type {string}
     * @memberof MintAddressCriterionRequest
     */
    'type': MintAddressCriterionRequestTypeEnum;
    /**
     * The operator to use for comparison.
     * @type {string}
     * @memberof MintAddressCriterionRequest
     */
    'operator': MintAddressCriterionRequestOperatorEnum;
    /**
     * List of mint addresses (Base58).
     * @type {Array<string>}
     * @memberof MintAddressCriterionRequest
     */
    'addresses': Array<string>;
}

export const MintAddressCriterionRequestTypeEnum = {
    MintAddress: 'mintAddress'
} as const;

export type MintAddressCriterionRequestTypeEnum = typeof MintAddressCriterionRequestTypeEnum[keyof typeof MintAddressCriterionRequestTypeEnum];
export const MintAddressCriterionRequestOperatorEnum = {
    Equal: '==',
    In: 'in'
} as const;

export type MintAddressCriterionRequestOperatorEnum = typeof MintAddressCriterionRequestOperatorEnum[keyof typeof MintAddressCriterionRequestOperatorEnum];


