/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EvmCriteriaTypeNETUSDCHANGE } from './evm-criteria-type-netusdchange';
// May contain unused imports in some cases
// @ts-ignore
import { NetUSDChangeCriterionOperator } from './net-usdchange-criterion-operator';

/**
 * 
 * @export
 * @interface NetUSDChangeCriterion
 */
export interface NetUSDChangeCriterion {
    /**
     * 
     * @type {EvmCriteriaTypeNETUSDCHANGE}
     * @memberof NetUSDChangeCriterion
     */
    'type': EvmCriteriaTypeNETUSDCHANGE;
    /**
     * 
     * @type {NetUSDChangeCriterionOperator}
     * @memberof NetUSDChangeCriterion
     */
    'operator': NetUSDChangeCriterionOperator;
    /**
     * 
     * @type {string}
     * @memberof NetUSDChangeCriterion
     */
    'usdValue': string;
}



