/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A started, provider-hosted limit upgrade — embed the URL before it expires.
 * @export
 * @interface OnrampLimitUpgradeResponse
 */
export interface OnrampLimitUpgradeResponse {
    /**
     * Single-use and short-lived; request a fresh one per attempt.
     * @type {string}
     * @memberof OnrampLimitUpgradeResponse
     */
    'url': string;
    /**
     * ISO-8601.
     * @type {string}
     * @memberof OnrampLimitUpgradeResponse
     */
    'expiresAt': string;
}

