/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OnrampProvider } from './onramp-provider';

/**
 * Common unified request format for creating an onramp session. This format is provider-agnostic and will be adapted by each provider service.
 * @export
 * @interface OnrampSessionRequest
 */
export interface OnrampSessionRequest {
    /**
     * 
     * @type {OnrampProvider}
     * @memberof OnrampSessionRequest
     */
    'provider': OnrampProvider;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'destinationCurrency': string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'destinationNetwork': string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'destinationAddress': string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'sourceAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'sourceCurrency'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'redirectUrl'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'subdivision'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'paymentMethod'?: string;
    /**
     * 
     * @type {string}
     * @memberof OnrampSessionRequest
     */
    'clientIp'?: string;
}



