/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePAYMASTER } from './entity-type-paymaster';

/**
 * 
 * @export
 * @interface PaymasterResponse
 */
export interface PaymasterResponse {
    /**
     * 
     * @type {string}
     * @memberof PaymasterResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePAYMASTER}
     * @memberof PaymasterResponse
     */
    'object': EntityTypePAYMASTER;
    /**
     * 
     * @type {number}
     * @memberof PaymasterResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {string}
     * @memberof PaymasterResponse
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof PaymasterResponse
     */
    'url': string;
    /**
     * 
     * @type {object}
     * @memberof PaymasterResponse
     */
    'context'?: object;
}



