/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CryptoPaymentMethodRequest } from './crypto-payment-method-request';
// May contain unused imports in some cases
// @ts-ignore
import { FundingSourceRequest } from './funding-source-request';
// May contain unused imports in some cases
// @ts-ignore
import { OnrampPaymentMethodRequest } from './onramp-payment-method-request';
// May contain unused imports in some cases
// @ts-ignore
import { OnrampPaymentMethodRequestEmbedded } from './onramp-payment-method-request-embedded';

/**
 * A single payment method for a session — a crypto source or a fiat onramp.
 * @export
 * @interface PaymentMethodRequest
 */
export interface PaymentMethodRequest {
    /**
     * Self-custody source family.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'type': PaymentMethodRequestTypeEnum;
    /**
     * 
     * @type {FundingSourceRequest}
     * @memberof PaymentMethodRequest
     */
    'source': FundingSourceRequest;
    /**
     * Origin-chain refund address for an auto-bridged (chained) route — where the onramped intermediate is refunded if the Relay bridge to the target bounces. Only consulted when the route chains cross-VM (e.g. an EVM intermediate to a Solana target); same-VM chains refund to the target address automatically.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'refundTo'?: string;
    /**
     * The funding method the user picked.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'method': PaymentMethodRequestMethodEnum;
    /**
     * Fiat amount to prefill in the provider checkout, in the source currency\'s human units (decimal string). Omit to let the user choose in-checkout.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'sourceAmount'?: string;
    /**
     * ISO-4217 fiat currency for `sourceAmount`.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'sourceCurrency'?: string;
    /**
     * Explicit buyer country override (ISO-3166 alpha-2). Wins over the request IP — the escape hatch for QA and apps that already know their user\'s region.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'country'?: string;
    /**
     * URL the provider redirects back to after checkout.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'redirectUrl'?: string;
    /**
     * OTP-verified buyer email — REQUIRED for `apple_pay`/`google_pay` (the native wallet-pay sheet needs verified buyer identity). Ignored for `card`/`bank_transfer`. Openfort verifies it via its own email OTP.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'email'?: string;
    /**
     * OTP-verified US mobile in E.164 — REQUIRED for `apple_pay`/`google_pay`; the wallet-pay rail currently requires a verified US cell. Ignored for `card`/`bank_transfer`.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'phoneNumber'?: string;
    /**
     * ISO-8601 time the phone OTP was verified. REQUIRED for `apple_pay`/`google_pay`; must be recent enough for the wallet-pay rail\'s re-verify window.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'phoneNumberVerifiedAt'?: string;
    /**
     * ISO-8601 time the buyer accepted the checkout terms surfaced at the amount step. REQUIRED for `apple_pay`/`google_pay`.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'agreementAcceptedAt'?: string;
    /**
     * Verification record for the phone, from POST /v2/funding/onramp/verifications (channel \"sms\") + submit.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'smsVerificationId'?: string;
    /**
     * Verification record for the email, from POST /v2/funding/onramp/verifications (channel \"email\") + submit.
     * @type {string}
     * @memberof PaymentMethodRequest
     */
    'emailVerificationId'?: string;
    /**
     * 
     * @type {OnrampPaymentMethodRequestEmbedded}
     * @memberof PaymentMethodRequest
     */
    'embedded'?: OnrampPaymentMethodRequestEmbedded;
}

export const PaymentMethodRequestTypeEnum = {
    Evm: 'evm',
    Solana: 'solana',
    Onramp: 'onramp'
} as const;

export type PaymentMethodRequestTypeEnum = typeof PaymentMethodRequestTypeEnum[keyof typeof PaymentMethodRequestTypeEnum];
export const PaymentMethodRequestMethodEnum = {
    ApplePay: 'apple_pay',
    GooglePay: 'google_pay',
    Card: 'card',
    BankTransfer: 'bank_transfer'
} as const;

export type PaymentMethodRequestMethodEnum = typeof PaymentMethodRequestMethodEnum[keyof typeof PaymentMethodRequestMethodEnum];


