/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PhoneNumberForgetPasswordPostRequest
 */
export interface PhoneNumberForgetPasswordPostRequest {
    /**
     * The phone number which is associated with the user. Eg: \"+1234567890\"
     * @type {string}
     * @memberof PhoneNumberForgetPasswordPostRequest
     */
    'phoneNumber': string;
}

