/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BetterAuthSMSClientsVONAGE } from './better-auth-smsclients-vonage';

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
 */
export interface PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider {
    /**
     * 
     * @type {BetterAuthSMSClientsVONAGE}
     * @memberof PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
     */
    'senderClient': BetterAuthSMSClientsVONAGE;
    /**
     * 
     * @type {boolean}
     * @memberof PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
     */
    'enabled': boolean;
    /**
     * Vonage API Key
     * @type {string}
     * @memberof PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
     */
    'apiKey': string;
    /**
     * Vonage API Secret
     * @type {string}
     * @memberof PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
     */
    'apiSecret': string;
    /**
     * Sender ID or phone number
     * @type {string}
     * @memberof PickVonageSMSConfigExcludeKeyofVonageSMSConfigProvider
     */
    'from': string;
}



