/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
 */
export interface PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials {
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'ecosystem': string;
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'defaultChain': string;
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'defaultCurrency': string;
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'recommendedAmount': string;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'crossChainBridging': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'onrampEnabled': boolean;
    /**
     * Enabled web2 methods (FundingMethod values), in display order.
     * @type {Array<string>}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'onrampMethods': Array<string>;
    /**
     * Whether native wallet pay (Apple/Google Pay) is offered. Needs the project\'s own CDP keys.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'walletPayEnabled': boolean;
    /**
     * Whether Stripe\'s in-page (embedded) rail is offered. Needs the project\'s own Link OAuth client.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'stripeEnabled': boolean;
    /**
     * Whether hosted-checkout popup rows (including the rest-of-world fallback) are offered.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'hostedCheckoutEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'depositAddressEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'depositFromWalletEnabled': boolean;
    /**
     * The project\'s Stripe publishable key, handed to the client so the embedded component can initialize. Public by design — it belongs to the same Stripe account as the embedded credentials below, so it is per-project too.
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigCredentials
     */
    'stripePublishableKey': string;
}

