/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
 */
export interface PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey {
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'ecosystem': string;
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'defaultChain': string;
    /**
     * 
     * @type {string}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'defaultCurrency': string;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'crossChainBridging': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'onrampEnabled': boolean;
    /**
     * Enabled web2 methods (FundingMethod values), in display order.
     * @type {Array<string>}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'onrampMethods': Array<string>;
    /**
     * Whether native wallet pay (Apple/Google Pay) is offered. Needs the project\'s own CDP keys.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'walletPayEnabled': boolean;
    /**
     * Whether the Stripe rail is offered. With the project\'s own Link OAuth client it runs in-page (embedded); without one it degrades to the hosted popup on the project\'s secret key alone.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'stripeEnabled': boolean;
    /**
     * Whether Coinbase hosted-checkout popup rows (including the rest-of-world fallback) are offered.
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'hostedCheckoutEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'depositAddressEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PickFundingProjectConfigExcludeKeyofFundingProjectConfigRecommendedAmountOrCredentialsOrStripePublishableKey
     */
    'depositFromWalletEnabled': boolean;
}

