/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BetterAuthSMSClientsTWILIO } from './better-auth-smsclients-twilio';

/**
 * From T, pick a set of properties whose keys are in the union K
 * @export
 * @interface PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
 */
export interface PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider {
    /**
     * 
     * @type {BetterAuthSMSClientsTWILIO}
     * @memberof PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
     */
    'senderClient': BetterAuthSMSClientsTWILIO;
    /**
     * Twilio Account SID
     * @type {string}
     * @memberof PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
     */
    'accountSid': string;
    /**
     * Twilio Auth Token
     * @type {string}
     * @memberof PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
     */
    'authToken': string;
    /**
     * Twilio phone number (from)
     * @type {string}
     * @memberof PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
     */
    'phoneNumber': string;
    /**
     * 
     * @type {boolean}
     * @memberof PickTwilioSMSConfigExcludeKeyofTwilioSMSConfigProvider
     */
    'enabled': boolean;
}



