/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PlayerMetadataValue } from './player-metadata-value';

/**
 * 
 * @export
 * @interface PlayerCreateRequest
 */
export interface PlayerCreateRequest {
    /**
     * Specifies the player name.
     * @type {string}
     * @memberof PlayerCreateRequest
     */
    'name'?: string;
    /**
     * Specifies the player description.
     * @type {string}
     * @memberof PlayerCreateRequest
     */
    'description'?: string;
    /**
     * 
     * @type {{ [key: string]: PlayerMetadataValue; }}
     * @memberof PlayerCreateRequest
     */
    'metadata'?: { [key: string]: PlayerMetadataValue; };
}

