/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PlayerTransferOwnershipRequest
 */
export interface PlayerTransferOwnershipRequest {
    /**
     * ID of the Policy that defines the gas sponsorship strategy (starts with `pol_`). A policy must be provided.
     * @type {string}
     * @memberof PlayerTransferOwnershipRequest
     */
    'policy': string;
    /**
     * The chain ID. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof PlayerTransferOwnershipRequest
     */
    'chainId': number;
    /**
     * The address of the new owner
     * @type {string}
     * @memberof PlayerTransferOwnershipRequest
     */
    'newOwnerAddress': string;
    /**
     * ID of the Player that has the Account you want to transfer ownership from (starts with `pla_`).
     * @type {string}
     * @memberof PlayerTransferOwnershipRequest
     */
    'player'?: string;
}

