/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityIdResponse } from './entity-id-response';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePOLICY } from './entity-type-policy';
// May contain unused imports in some cases
// @ts-ignore
import { PlayerResponseTransactionIntentsInner } from './player-response-transaction-intents-inner';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyResponsePolicyRulesInner } from './policy-response-policy-rules-inner';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyStrategy } from './policy-strategy';

/**
 * 
 * @export
 * @interface PolicyResponse
 */
export interface PolicyResponse {
    /**
     * 
     * @type {string}
     * @memberof PolicyResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePOLICY}
     * @memberof PolicyResponse
     */
    'object': EntityTypePOLICY;
    /**
     * 
     * @type {number}
     * @memberof PolicyResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {string}
     * @memberof PolicyResponse
     */
    'name': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof PolicyResponse
     */
    'deleted': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PolicyResponse
     */
    'enabled': boolean;
    /**
     * The chain ID.
     * @type {number}
     * @memberof PolicyResponse
     */
    'chainId': number;
    /**
     * 
     * @type {EntityIdResponse}
     * @memberof PolicyResponse
     */
    'paymaster'?: EntityIdResponse;
    /**
     * 
     * @type {EntityIdResponse}
     * @memberof PolicyResponse
     */
    'forwarderContract'?: EntityIdResponse;
    /**
     * 
     * @type {PolicyStrategy}
     * @memberof PolicyResponse
     */
    'strategy': PolicyStrategy;
    /**
     * 
     * @type {Array<PlayerResponseTransactionIntentsInner>}
     * @memberof PolicyResponse
     */
    'transactionIntents': Array<PlayerResponseTransactionIntentsInner>;
    /**
     * 
     * @type {Array<PolicyResponsePolicyRulesInner>}
     * @memberof PolicyResponse
     */
    'policyRules': Array<PolicyResponsePolicyRulesInner>;
}



