/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountPolicyRuleResponse } from './account-policy-rule-response';
// May contain unused imports in some cases
// @ts-ignore
import { ContractPolicyRuleResponse } from './contract-policy-rule-response';
// May contain unused imports in some cases
// @ts-ignore
import { ContractPolicyRuleResponseContract } from './contract-policy-rule-response-contract';
// May contain unused imports in some cases
// @ts-ignore
import { CountPerIntervalLimitPolicyRuleResponse } from './count-per-interval-limit-policy-rule-response';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePOLICYRULE } from './entity-type-policyrule';
// May contain unused imports in some cases
// @ts-ignore
import { GasPerIntervalLimitPolicyRuleResponse } from './gas-per-interval-limit-policy-rule-response';
// May contain unused imports in some cases
// @ts-ignore
import { GasPerTransactionLimitPolicyRuleResponse } from './gas-per-transaction-limit-policy-rule-response';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyRateLimitCOUNTPERINTERVAL } from './policy-rate-limit-countperinterval';
// May contain unused imports in some cases
// @ts-ignore
import { PolicyRuleTypeRATELIMIT } from './policy-rule-type-ratelimit';
// May contain unused imports in some cases
// @ts-ignore
import { TimeIntervalType } from './time-interval-type';

/**
 * 
 * @export
 * @interface PolicyRuleResponse
 */
export interface PolicyRuleResponse {
    /**
     * 
     * @type {string}
     * @memberof PolicyRuleResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePOLICYRULE}
     * @memberof PolicyRuleResponse
     */
    'object': EntityTypePOLICYRULE;
    /**
     * 
     * @type {number}
     * @memberof PolicyRuleResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {PolicyRuleTypeRATELIMIT}
     * @memberof PolicyRuleResponse
     */
    'type': PolicyRuleTypeRATELIMIT;
    /**
     * 
     * @type {ContractPolicyRuleResponseContract}
     * @memberof PolicyRuleResponse
     */
    'contract'?: ContractPolicyRuleResponseContract;
    /**
     * 
     * @type {PolicyRateLimitCOUNTPERINTERVAL}
     * @memberof PolicyRuleResponse
     */
    'functionName': PolicyRateLimitCOUNTPERINTERVAL;
    /**
     * 
     * @type {boolean}
     * @memberof PolicyRuleResponse
     */
    'wildcard': boolean;
    /**
     * 
     * @type {string}
     * @memberof PolicyRuleResponse
     */
    'gasLimit': string;
    /**
     * 
     * @type {TimeIntervalType}
     * @memberof PolicyRuleResponse
     */
    'timeIntervalType': TimeIntervalType;
    /**
     * 
     * @type {number}
     * @memberof PolicyRuleResponse
     */
    'timeIntervalValue': number;
    /**
     * 
     * @type {number}
     * @memberof PolicyRuleResponse
     */
    'countLimit': number;
}



