/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const PolicyRateLimit = {
    GasPerTransaction: 'gas_per_transaction',
    GasPerInterval: 'gas_per_interval',
    CountPerInterval: 'count_per_interval'
} as const;

export type PolicyRateLimit = typeof PolicyRateLimit[keyof typeof PolicyRateLimit];



