/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrismaSortOrder } from './prisma-sort-order';

/**
 * 
 * @export
 * @interface PolicyV2ListQueries
 */
export interface PolicyV2ListQueries {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof PolicyV2ListQueries
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof PolicyV2ListQueries
     */
    'skip'?: number;
    /**
     * 
     * @type {PrismaSortOrder}
     * @memberof PolicyV2ListQueries
     */
    'order'?: PrismaSortOrder;
    /**
     * Filter by scope.
     * @type {Array<string>}
     * @memberof PolicyV2ListQueries
     */
    'scope'?: Array<PolicyV2ListQueriesScopeEnum>;
    /**
     * Filter by enabled status.
     * @type {boolean}
     * @memberof PolicyV2ListQueries
     */
    'enabled'?: boolean;
    /**
     * Filter by account ID (for account-scoped policies).
     * @type {string}
     * @memberof PolicyV2ListQueries
     */
    'accountId'?: string;
    /**
     * Only include policies that have at least one rule with an operation in this list.
     * @type {Array<string>}
     * @memberof PolicyV2ListQueries
     */
    'operation'?: Array<string>;
    /**
     * Exclude policies where all rules have operations in this list.
     * @type {Array<string>}
     * @memberof PolicyV2ListQueries
     */
    'operationNotIn'?: Array<string>;
}

export const PolicyV2ListQueriesScopeEnum = {
    Project: 'project',
    Account: 'account',
    Transaction: 'transaction'
} as const;

export type PolicyV2ListQueriesScopeEnum = typeof PolicyV2ListQueriesScopeEnum[keyof typeof PolicyV2ListQueriesScopeEnum];


