/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ThirdPartyOAuthProvider } from './third-party-oauth-provider';

/**
 * 
 * @export
 * @interface PregenerateUserRequestV2
 */
export interface PregenerateUserRequestV2 {
    /**
     * The email address of the user to pregenerate. Required if thirdPartyUserId is not provided.
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'email'?: string;
    /**
     * The third-party user ID from an external auth provider (Firebase, Supabase, etc.). Required if email is not provided.
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'thirdPartyUserId'?: string;
    /**
     * 
     * @type {ThirdPartyOAuthProvider}
     * @memberof PregenerateUserRequestV2
     */
    'thirdPartyProvider'?: ThirdPartyOAuthProvider;
    /**
     * The type of account to pregenerate. \"Externally Owned Account\", \"Smart Account\" or \"Delegated Account\". Defaults to \"Smart Account\".
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'accountType'?: PregenerateUserRequestV2AccountTypeEnum;
    /**
     * The chain type. \"EVM\" or \"SVM\". Defaults to \"EVM\".
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'chainType'?: PregenerateUserRequestV2ChainTypeEnum;
    /**
     * The chain ID. Required for Smart Account and Delegated Account types. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof PregenerateUserRequestV2
     */
    'chainId'?: number;
    /**
     * The implementation type for Smart Account or Delegated Account (e.g. Calibur, UpgradeableV6). Required for Smart Account and Delegated Account types.
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'implementationType'?: string;
}

export const PregenerateUserRequestV2AccountTypeEnum = {
    ExternallyOwnedAccount: 'Externally Owned Account',
    SmartAccount: 'Smart Account',
    DelegatedAccount: 'Delegated Account'
} as const;

export type PregenerateUserRequestV2AccountTypeEnum = typeof PregenerateUserRequestV2AccountTypeEnum[keyof typeof PregenerateUserRequestV2AccountTypeEnum];
export const PregenerateUserRequestV2ChainTypeEnum = {
    Evm: 'EVM',
    Svm: 'SVM'
} as const;

export type PregenerateUserRequestV2ChainTypeEnum = typeof PregenerateUserRequestV2ChainTypeEnum[keyof typeof PregenerateUserRequestV2ChainTypeEnum];


