/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PregenerateAccountConfig } from './pregenerate-account-config';
// May contain unused imports in some cases
// @ts-ignore
import { ThirdPartyOAuthProvider } from './third-party-oauth-provider';

/**
 * 
 * @export
 * @interface PregenerateUserRequestV2
 */
export interface PregenerateUserRequestV2 {
    /**
     * The email address of the user to pregenerate. Required if thirdPartyUserId is not provided.
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'email'?: string;
    /**
     * The third-party user ID from an external auth provider (Firebase, Supabase, etc.). Required if email is not provided.
     * @type {string}
     * @memberof PregenerateUserRequestV2
     */
    'thirdPartyUserId'?: string;
    /**
     * 
     * @type {ThirdPartyOAuthProvider}
     * @memberof PregenerateUserRequestV2
     */
    'thirdPartyProvider'?: ThirdPartyOAuthProvider;
    /**
     * One or more embedded accounts to pregenerate for the user. Each entry produces its own key material and recovery share. Use this to pregenerate accounts on different chain types (e.g. EVM and SVM) in a single call.
     * @type {Array<PregenerateAccountConfig>}
     * @memberof PregenerateUserRequestV2
     */
    'accounts': Array<PregenerateAccountConfig>;
}



