/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { RecoveryMethodDetails } from './recovery-method-details';
// May contain unused imports in some cases
// @ts-ignore
import { SmartAccountData } from './smart-account-data';

/**
 * 
 * @export
 * @interface PregenerateAccountEntry
 */
export interface PregenerateAccountEntry {
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'wallet': string;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'accountType': string;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'address': string;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'ownerAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'chainType': string;
    /**
     * 
     * @type {number}
     * @memberof PregenerateAccountEntry
     */
    'chainId'?: number;
    /**
     * 
     * @type {number}
     * @memberof PregenerateAccountEntry
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof PregenerateAccountEntry
     */
    'updatedAt': number;
    /**
     * 
     * @type {SmartAccountData}
     * @memberof PregenerateAccountEntry
     */
    'smartAccount'?: SmartAccountData;
    /**
     * 
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'recoveryMethod'?: string;
    /**
     * 
     * @type {RecoveryMethodDetails}
     * @memberof PregenerateAccountEntry
     */
    'recoveryMethodDetails'?: RecoveryMethodDetails;
    /**
     * Indicates key custody: \"Developer\" for TEE managed keys, \"User\" for user-managed keys.
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'custody': PregenerateAccountEntryCustodyEnum;
    /**
     * The recovery share for this embedded account\'s signer. This should be stored securely and provided to the user for account recovery.
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'recoveryShare': string;
    /**
     * The signer UUID (starts with `sig_`) backing this embedded account. Use this value as the `reference` when storing the recovery share with Shield, so subsequent reads of the account can resolve the recovery method via the signer-reference lookup.
     * @type {string}
     * @memberof PregenerateAccountEntry
     */
    'signer': string;
}

export const PregenerateAccountEntryCustodyEnum = {
    Developer: 'Developer',
    User: 'User'
} as const;

export type PregenerateAccountEntryCustodyEnum = typeof PregenerateAccountEntryCustodyEnum[keyof typeof PregenerateAccountEntryCustodyEnum];


