/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CodeChallenge } from './code-challenge';

/**
 * 
 * @export
 * @interface RequestResetPasswordRequest
 */
export interface RequestResetPasswordRequest {
    /**
     * The email address of the user.
     * @type {string}
     * @memberof RequestResetPasswordRequest
     */
    'email': string;
    /**
     * The URL sent to the user by email to reset the password. At the end of the URL, we will add the token in the format `?token=token`.
     * @type {string}
     * @memberof RequestResetPasswordRequest
     */
    'redirectUrl': string;
    /**
     * Unique value to identify the request. It\'s used to mitigate CSRF attacks.
     * @type {string}
     * @memberof RequestResetPasswordRequest
     */
    'state'?: string;
    /**
     * 
     * @type {CodeChallenge}
     * @memberof RequestResetPasswordRequest
     */
    'challenge'?: CodeChallenge;
}

