/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TransactionResponseLog } from './transaction-response-log';

/**
 * 
 * @export
 * @interface ResponseResponse
 */
export interface ResponseResponse {
    /**
     * The unix timestamp in seconds when the transactionIntent was created.
     * @type {number}
     * @memberof ResponseResponse
     */
    'createdAt': number;
    /**
     * The block height (number) of the block including the transaction of this log.
     * @type {number}
     * @memberof ResponseResponse
     */
    'blockNumber'?: number;
    /**
     * The transaction hash of the transaction of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'transactionHash'?: string;
    /**
     * The l1 gas used by the transaction of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'l1GasUsed'?: string;
    /**
     * The gas used by the transaction of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'gasUsed'?: string;
    /**
     * The gas fee by the transaction of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'gasFee'?: string;
    /**
     * The l1 gas fee by the transaction of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'l1GasFee'?: string;
    /**
     * The status of the transaction of this log.
     * @type {number}
     * @memberof ResponseResponse
     */
    'status'?: number;
    /**
     * The logs of the transaction of this log.
     * @type {Array<TransactionResponseLog>}
     * @memberof ResponseResponse
     */
    'logs'?: Array<TransactionResponseLog>;
    /**
     * The address of the contract of this log.
     * @type {string}
     * @memberof ResponseResponse
     */
    'to'?: string;
    /**
     * The error of the transaction of this log.
     * @type {any}
     * @memberof ResponseResponse
     */
    'error'?: any;
}

