/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from revoking a wallet secret.
 * @export
 * @interface RevokeWalletSecretResponse
 */
export interface RevokeWalletSecretResponse {
    /**
     * The type of object.
     * @type {string}
     * @memberof RevokeWalletSecretResponse
     */
    'object': RevokeWalletSecretResponseObjectEnum;
    /**
     * The key ID of the revoked secret.
     * @type {string}
     * @memberof RevokeWalletSecretResponse
     */
    'keyId': string;
    /**
     * Whether the secret was successfully revoked.
     * @type {boolean}
     * @memberof RevokeWalletSecretResponse
     */
    'revoked': boolean;
    /**
     * Timestamp when the secret was revoked (Unix epoch seconds).
     * @type {number}
     * @memberof RevokeWalletSecretResponse
     */
    'revokedAt': number;
}

export const RevokeWalletSecretResponseObjectEnum = {
    WalletSecretRevocation: 'walletSecretRevocation'
} as const;

export type RevokeWalletSecretResponseObjectEnum = typeof RevokeWalletSecretResponseObjectEnum[keyof typeof RevokeWalletSecretResponseObjectEnum];


