/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignUpEmailPost200ResponseUser
 */
export interface SignUpEmailPost200ResponseUser {
    /**
     * The unique identifier of the user
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'id': string;
    /**
     * The email address of the user
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'email': string;
    /**
     * The name of the user
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'name': string;
    /**
     * The profile image URL of the user
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'image'?: string | null;
    /**
     * Whether the email has been verified
     * @type {boolean}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'emailVerified': boolean;
    /**
     * When the user was created
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'createdAt': string;
    /**
     * When the user was last updated
     * @type {string}
     * @memberof SignUpEmailPost200ResponseUser
     */
    'updatedAt': string;
}

