/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignerListQueries
 */
export interface SignerListQueries {
    /**
     * 
     * @type {number}
     * @memberof SignerListQueries
     */
    'limit'?: number;
    /**
     * 
     * @type {number}
     * @memberof SignerListQueries
     */
    'skip'?: number;
    /**
     * 
     * @type {string}
     * @memberof SignerListQueries
     */
    'order'?: SignerListQueriesOrderEnum;
    /**
     * 
     * @type {string}
     * @memberof SignerListQueries
     */
    'signerType'?: string;
    /**
     * 
     * @type {string}
     * @memberof SignerListQueries
     */
    'account'?: string;
}

export const SignerListQueriesOrderEnum = {
    Asc: 'asc',
    Desc: 'desc'
} as const;

export type SignerListQueriesOrderEnum = typeof SignerListQueriesOrderEnum[keyof typeof SignerListQueriesOrderEnum];


