/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Response from signing data via backend wallet.
 * @export
 * @interface SignResponse
 */
export interface SignResponse {
    /**
     * The type of object.
     * @type {string}
     * @memberof SignResponse
     */
    'object': SignResponseObjectEnum;
    /**
     * The account ID that signed the data (starts with `acc_`).
     * @type {string}
     * @memberof SignResponse
     */
    'account': string;
    /**
     * The signature bytes (hex-encoded).
     * @type {string}
     * @memberof SignResponse
     */
    'signature': string;
}

export const SignResponseObjectEnum = {
    Signature: 'signature'
} as const;

export type SignResponseObjectEnum = typeof SignResponseObjectEnum[keyof typeof SignResponseObjectEnum];


