/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignUpEmailPostRequest
 */
export interface SignUpEmailPostRequest {
    /**
     * The name of the user
     * @type {string}
     * @memberof SignUpEmailPostRequest
     */
    'name': string;
    /**
     * The email of the user
     * @type {string}
     * @memberof SignUpEmailPostRequest
     */
    'email': string;
    /**
     * The password of the user
     * @type {string}
     * @memberof SignUpEmailPostRequest
     */
    'password': string;
    /**
     * The profile image URL of the user
     * @type {string}
     * @memberof SignUpEmailPostRequest
     */
    'image'?: string;
    /**
     * The URL to use for email verification callback
     * @type {string}
     * @memberof SignUpEmailPostRequest
     */
    'callbackURL'?: string;
    /**
     * If this is false, the session will not be remembered. Default is `true`.
     * @type {boolean}
     * @memberof SignUpEmailPostRequest
     */
    'rememberMe'?: boolean;
}

