/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SignInEmailPost200ResponseUser
 */
export interface SignInEmailPost200ResponseUser {
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'image'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof SignInEmailPost200ResponseUser
     */
    'emailVerified': boolean;
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof SignInEmailPost200ResponseUser
     */
    'updatedAt': string;
}

