/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SiweVerifyPostRequest
 */
export interface SiweVerifyPostRequest {
    /**
     * The SIWE message string that was signed
     * @type {string}
     * @memberof SiweVerifyPostRequest
     */
    'message': string;
    /**
     * The signature from the user\'s wallet
     * @type {string}
     * @memberof SiweVerifyPostRequest
     */
    'signature': string;
    /**
     * Ethereum wallet address (must be 42 characters starting with 0x)
     * @type {string}
     * @memberof SiweVerifyPostRequest
     */
    'walletAddress': string;
    /**
     * Blockchain network chain ID (must match the Chain ID in SIWE message, default: 1)
     * @type {number}
     * @memberof SiweVerifyPostRequest
     */
    'chainId'?: number;
    /**
     * Email address (required if anonymous mode is disabled)
     * @type {string}
     * @memberof SiweVerifyPostRequest
     */
    'email'?: string;
}

