/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SiweVerifyPost200ResponseUser
 */
export interface SiweVerifyPost200ResponseUser {
    /**
     * User ID
     * @type {string}
     * @memberof SiweVerifyPost200ResponseUser
     */
    'id': string;
    /**
     * Ethereum wallet address
     * @type {string}
     * @memberof SiweVerifyPost200ResponseUser
     */
    'walletAddress': string;
    /**
     * Chain ID used for authentication
     * @type {number}
     * @memberof SiweVerifyPost200ResponseUser
     */
    'chainId': number;
}

