/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SiweVerifyPost401Response
 */
export interface SiweVerifyPost401Response {
    /**
     * 
     * @type {string}
     * @memberof SiweVerifyPost401Response
     */
    'message': string;
    /**
     * Error code (e.g., UNAUTHORIZED_INVALID_OR_EXPIRED_NONCE)
     * @type {string}
     * @memberof SiweVerifyPost401Response
     */
    'code'?: string;
}

