/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SocialSignInRequestIdToken
 */
export interface SocialSignInRequestIdToken {
    /**
     * ID token from the provider
     * @type {string}
     * @memberof SocialSignInRequestIdToken
     */
    'token': string;
    /**
     * Nonce used to generate the token
     * @type {string}
     * @memberof SocialSignInRequestIdToken
     */
    'nonce'?: string | null;
    /**
     * Access token from the provider
     * @type {string}
     * @memberof SocialSignInRequestIdToken
     */
    'accessToken'?: string | null;
    /**
     * Refresh token from the provider
     * @type {string}
     * @memberof SocialSignInRequestIdToken
     */
    'refreshToken'?: string | null;
    /**
     * Expiry date of the token
     * @type {number}
     * @memberof SocialSignInRequestIdToken
     */
    'expiresAt'?: number | null;
}

