/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EvmAddressCriterionOperator } from './evm-address-criterion-operator';
// May contain unused imports in some cases
// @ts-ignore
import { SolanaCriteriaTypeSOLNETWORK } from './solana-criteria-type-solnetwork';

/**
 * 
 * @export
 * @interface SolNetworkCriterion
 */
export interface SolNetworkCriterion {
    /**
     * 
     * @type {SolanaCriteriaTypeSOLNETWORK}
     * @memberof SolNetworkCriterion
     */
    'type': SolanaCriteriaTypeSOLNETWORK;
    /**
     * 
     * @type {EvmAddressCriterionOperator}
     * @memberof SolNetworkCriterion
     */
    'operator': EvmAddressCriterionOperator;
    /**
     * 
     * @type {Array<string>}
     * @memberof SolNetworkCriterion
     */
    'networks': Array<string>;
}



