/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CriteriaOperatorMATCH } from './criteria-operator-match';
// May contain unused imports in some cases
// @ts-ignore
import { SolanaCriteriaTypeSOLMESSAGE } from './solana-criteria-type-solmessage';

/**
 * 
 * @export
 * @interface SolMessageCriterion
 */
export interface SolMessageCriterion {
    /**
     * 
     * @type {SolanaCriteriaTypeSOLMESSAGE}
     * @memberof SolMessageCriterion
     */
    'type': SolanaCriteriaTypeSOLMESSAGE;
    /**
     * 
     * @type {CriteriaOperatorMATCH}
     * @memberof SolMessageCriterion
     */
    'operator': CriteriaOperatorMATCH;
    /**
     * 
     * @type {string}
     * @memberof SolMessageCriterion
     */
    'pattern': string;
}



