/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubmitTransactionSignatureRequestV2
 */
export interface SubmitTransactionSignatureRequestV2 {
    /**
     * Signature of `nextAction.hash` by the account owner or a valid session key.
     * @type {string}
     * @memberof SubmitTransactionSignatureRequestV2
     */
    'signature': string;
    /**
     * Whether to hold the request until the transaction is mined and the `receipt` is available (default `true`). Set to `false` to respond as soon as the transaction is broadcast (`status: \"submitted\"`) and poll `GET /v2/transactions/{id}` for the outcome.
     * @type {boolean}
     * @memberof SubmitTransactionSignatureRequestV2
     */
    'waitForReceipt'?: boolean;
}

