/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OAuthProviderTELEGRAM } from './oauth-provider-telegram';

/**
 * 
 * @export
 * @interface TelegramOAuthConfig
 */
export interface TelegramOAuthConfig {
    /**
     * Enable OAuth provider.
     * @type {boolean}
     * @memberof TelegramOAuthConfig
     */
    'enabled': boolean;
    /**
     * 
     * @type {OAuthProviderTELEGRAM}
     * @memberof TelegramOAuthConfig
     */
    'provider': OAuthProviderTELEGRAM;
    /**
     * Telegram bot username.
     * @type {string}
     * @memberof TelegramOAuthConfig
     */
    'botUsername': string;
    /**
     * Telegram bot token.
     * @type {string}
     * @memberof TelegramOAuthConfig
     */
    'botToken': string;
}



