/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @enum {string}
 */

export const TransactionAbstractionType = {
    AccountAbstractionV6: 'accountAbstractionV6',
    AccountAbstractionV8: 'accountAbstractionV8',
    AccountAbstractionV9: 'accountAbstractionV9',
    ZkSync: 'zkSync',
    Standard: 'standard'
} as const;

export type TransactionAbstractionType = typeof TransactionAbstractionType[keyof typeof TransactionAbstractionType];



