/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TransactionEventV2 } from './transaction-event-v2';

/**
 * 
 * @export
 * @interface TransactionTimelineEntryV2
 */
export interface TransactionTimelineEntryV2 {
    /**
     * 
     * @type {TransactionEventV2}
     * @memberof TransactionTimelineEntryV2
     */
    'event': TransactionEventV2;
    /**
     * Unix timestamp (seconds). Absent when the exact time is unknown (e.g. `submitted` for a transaction the monitor did not track).
     * @type {number}
     * @memberof TransactionTimelineEntryV2
     */
    'at'?: number;
}



