/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityIdResponse } from './entity-id-response';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypePLAYER } from './entity-type-player';
// May contain unused imports in some cases
// @ts-ignore
import { Player } from './player';
// May contain unused imports in some cases
// @ts-ignore
import { PlayerMetadataValue } from './player-metadata-value';

/**
 * The player ID (starts with pla_).
 * @export
 * @interface TransactionIntentResponsePlayer
 */
export interface TransactionIntentResponsePlayer {
    /**
     * 
     * @type {string}
     * @memberof TransactionIntentResponsePlayer
     */
    'id': string;
    /**
     * 
     * @type {EntityTypePLAYER}
     * @memberof TransactionIntentResponsePlayer
     */
    'object': EntityTypePLAYER;
    /**
     * 
     * @type {number}
     * @memberof TransactionIntentResponsePlayer
     */
    'createdAt': number;
    /**
     * 
     * @type {string}
     * @memberof TransactionIntentResponsePlayer
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TransactionIntentResponsePlayer
     */
    'description'?: string;
    /**
     * 
     * @type {{ [key: string]: PlayerMetadataValue; }}
     * @memberof TransactionIntentResponsePlayer
     */
    'metadata'?: { [key: string]: PlayerMetadataValue; };
    /**
     * 
     * @type {Array<EntityIdResponse>}
     * @memberof TransactionIntentResponsePlayer
     */
    'transactionIntents'?: Array<EntityIdResponse>;
    /**
     * 
     * @type {Array<EntityIdResponse>}
     * @memberof TransactionIntentResponsePlayer
     */
    'accounts'?: Array<EntityIdResponse>;
}



