/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountAbstractionV6Details } from './account-abstraction-v6-details';
// May contain unused imports in some cases
// @ts-ignore
import { AccountAbstractionV8Details } from './account-abstraction-v8-details';
// May contain unused imports in some cases
// @ts-ignore
import { AccountAbstractionV9Details } from './account-abstraction-v9-details';
// May contain unused imports in some cases
// @ts-ignore
import { StandardDetails } from './standard-details';
// May contain unused imports in some cases
// @ts-ignore
import { UserOperationV9 } from './user-operation-v9';
// May contain unused imports in some cases
// @ts-ignore
import { ZKSyncDetails } from './zksync-details';

/**
 * Specific transaction details based on its type
 * @export
 * @interface TransactionIntentResponseDetails
 */
export interface TransactionIntentResponseDetails {
    /**
     * The transaction sender.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'from': string;
    /**
     * The transaction recipient or contract address.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'to': string;
    /**
     * A contract hashed method call with encoded args.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'data'?: string;
    /**
     * Unique number identifying this transaction.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'nonce': string;
    /**
     * The gas limit for the transaction.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'gas': string;
    /**
     * Total fee per gas (in wei), inclusive of `maxPriorityFeePerGas`. Only applies to EIP-1559 Transactions.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'maxFeePerGas': string;
    /**
     * Max priority fee per gas (in wei). Only applies to EIP-1559 Transactions.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'maxPriorityFeePerGas': string;
    /**
     * Address of the paymaster account that will pay the fees.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'paymaster'?: string;
    /**
     * Input data to the paymaster
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'paymasterInput'?: string;
    /**
     * Value in wei sent with this transaction.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'value'?: string;
    /**
     * 
     * @type {UserOperationV9}
     * @memberof TransactionIntentResponseDetails
     */
    'userOperation': UserOperationV9;
    /**
     * A User Operation hash.
     * @type {string}
     * @memberof TransactionIntentResponseDetails
     */
    'userOperationHash': string;
}

