/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AccountV2Response } from './account-v2-response';
// May contain unused imports in some cases
// @ts-ignore
import { AuthUserResponse } from './auth-user-response';
// May contain unused imports in some cases
// @ts-ignore
import { EntityTypeTRANSACTION } from './entity-type-transaction';
// May contain unused imports in some cases
// @ts-ignore
import { FeeSponsorshipResponse } from './fee-sponsorship-response';
// May contain unused imports in some cases
// @ts-ignore
import { Interaction } from './interaction';
// May contain unused imports in some cases
// @ts-ignore
import { SignHashAction } from './sign-hash-action';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionReceiptV2 } from './transaction-receipt-v2';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionResponseV2Execution } from './transaction-response-v2-execution';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionStatusV2 } from './transaction-status-v2';
// May contain unused imports in some cases
// @ts-ignore
import { TransactionTimelineEntryV2 } from './transaction-timeline-entry-v2';

/**
 * 
 * @export
 * @interface TransactionResponseV2
 */
export interface TransactionResponseV2 {
    /**
     * 
     * @type {string}
     * @memberof TransactionResponseV2
     */
    'id': string;
    /**
     * 
     * @type {EntityTypeTRANSACTION}
     * @memberof TransactionResponseV2
     */
    'object': EntityTypeTRANSACTION;
    /**
     * 
     * @type {number}
     * @memberof TransactionResponseV2
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof TransactionResponseV2
     */
    'updatedAt': number;
    /**
     * 
     * @type {number}
     * @memberof TransactionResponseV2
     */
    'chainId': number;
    /**
     * 
     * @type {TransactionStatusV2}
     * @memberof TransactionResponseV2
     */
    'status': TransactionStatusV2;
    /**
     * ID of the account that executes the transaction (starts with `acc_`).
     * @type {string}
     * @memberof TransactionResponseV2
     */
    'accountId': string;
    /**
     * ID of the wallet that owns the account (starts with `pla_`). Absent for backend wallets.
     * @type {string}
     * @memberof TransactionResponseV2
     */
    'walletId'?: string;
    /**
     * ID of the fee sponsorship paying for gas (starts with `pol_`). Absent when the account pays its own gas.
     * @type {string}
     * @memberof TransactionResponseV2
     */
    'feeSponsorshipId'?: string;
    /**
     * 
     * @type {AccountV2Response}
     * @memberof TransactionResponseV2
     */
    'account'?: AccountV2Response;
    /**
     * 
     * @type {AuthUserResponse}
     * @memberof TransactionResponseV2
     */
    'user'?: AuthUserResponse;
    /**
     * 
     * @type {FeeSponsorshipResponse}
     * @memberof TransactionResponseV2
     */
    'feeSponsorship'?: FeeSponsorshipResponse;
    /**
     * The calls this transaction executes.
     * @type {Array<Interaction>}
     * @memberof TransactionResponseV2
     */
    'calls'?: Array<Interaction>;
    /**
     * 
     * @type {TransactionResponseV2Execution}
     * @memberof TransactionResponseV2
     */
    'execution'?: TransactionResponseV2Execution;
    /**
     * 
     * @type {SignHashAction}
     * @memberof TransactionResponseV2
     */
    'nextAction'?: SignHashAction;
    /**
     * 
     * @type {TransactionReceiptV2}
     * @memberof TransactionResponseV2
     */
    'receipt'?: TransactionReceiptV2;
    /**
     * Lifecycle history in order, present only with `expand=timeline`. Status-valued events come from this API\'s own records and always agree with `status`; monitoring-only events (`indexed`, `confirmed`, `dropped`, `replaced`, `expired`) come from the user-operation monitor, are best-effort, and are never present for plain EOA transactions.
     * @type {Array<TransactionTimelineEntryV2>}
     * @memberof TransactionResponseV2
     */
    'timeline'?: Array<TransactionTimelineEntryV2>;
    /**
     * The actual transaction cost in USD, available after on-chain confirmation.
     * @type {string}
     * @memberof TransactionResponseV2
     */
    'costUsd'?: string;
}



