/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OAuthProviderTWITTER } from './oauth-provider-twitter';

/**
 * Twitter oauth configuration
 * @export
 * @interface TwitterOAuthConfig
 */
export interface TwitterOAuthConfig {
    /**
     * Enable OAuth provider.
     * @type {boolean}
     * @memberof TwitterOAuthConfig
     */
    'enabled': boolean;
    /**
     * 
     * @type {OAuthProviderTWITTER}
     * @memberof TwitterOAuthConfig
     */
    'provider': OAuthProviderTWITTER;
    /**
     * Twitter API consumer key.
     * @type {string}
     * @memberof TwitterOAuthConfig
     */
    'clientId': string;
    /**
     * Twitter API consumer secret.
     * @type {string}
     * @memberof TwitterOAuthConfig
     */
    'clientSecret': string;
}



