/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { OAuthProvider } from './oauth-provider';

/**
 * The request to verify access token
 * @export
 * @interface UnlinkOAuthRequest
 */
export interface UnlinkOAuthRequest {
    /**
     * 
     * @type {OAuthProvider}
     * @memberof UnlinkOAuthRequest
     */
    'provider': OAuthProvider;
}



