/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ApiKeyType } from './api-key-type';

/**
 * 
 * @export
 * @interface UpdateProjectApiKeyRequest
 */
export interface UpdateProjectApiKeyRequest {
    /**
     * 
     * @type {ApiKeyType}
     * @memberof UpdateProjectApiKeyRequest
     */
    'type': ApiKeyType;
    /**
     * The API key to update.
     * @type {string}
     * @memberof UpdateProjectApiKeyRequest
     */
    'uuid': string;
    /**
     * Whether key to use to sign webhooks.
     * @type {boolean}
     * @memberof UpdateProjectApiKeyRequest
     */
    'use_for_webhooks'?: boolean;
}



