/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FundingConfigCoinbaseRequest } from './funding-config-coinbase-request';

/**
 * Body for PUT /v2/funding/config — the dashboard \"Funding\" section config.
 * @export
 * @interface UpdateFundingConfigRequest
 */
export interface UpdateFundingConfigRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateFundingConfigRequest
     */
    'ecosystem': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFundingConfigRequest
     */
    'defaultChain': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFundingConfigRequest
     */
    'defaultCurrency': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateFundingConfigRequest
     */
    'recommendedAmount'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFundingConfigRequest
     */
    'crossChainBridging': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFundingConfigRequest
     */
    'onrampEnabled': boolean;
    /**
     * Enabled web2 methods (apple_pay | google_pay | card | bank_transfer), in order.
     * @type {Array<string>}
     * @memberof UpdateFundingConfigRequest
     */
    'onrampMethods': Array<string>;
    /**
     * 
     * @type {FundingConfigCoinbaseRequest}
     * @memberof UpdateFundingConfigRequest
     */
    'coinbase'?: FundingConfigCoinbaseRequest;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFundingConfigRequest
     */
    'depositAddressEnabled': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateFundingConfigRequest
     */
    'depositFromWalletEnabled': boolean;
}

