/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreatePolicyV2RuleRequest } from './create-policy-v2-rule-request';

/**
 * 
 * @export
 * @interface UpdatePolicyV2Request
 */
export interface UpdatePolicyV2Request {
    /**
     * A description of what this policy does.
     * @type {string}
     * @memberof UpdatePolicyV2Request
     */
    'description'?: string;
    /**
     * Whether the policy is enabled.
     * @type {boolean}
     * @memberof UpdatePolicyV2Request
     */
    'enabled'?: boolean;
    /**
     * Priority of the policy. Higher priority policies are evaluated first.
     * @type {number}
     * @memberof UpdatePolicyV2Request
     */
    'priority'?: number;
    /**
     * The rules that make up this policy. If provided, replaces all existing rules.
     * @type {Array<CreatePolicyV2RuleRequest>}
     * @memberof UpdatePolicyV2Request
     */
    'rules'?: Array<CreatePolicyV2RuleRequest>;
}

