/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthorizedNetwork } from './authorized-network';

/**
 * 
 * @export
 * @interface UpdateAuthorizedNetworksRequest
 */
export interface UpdateAuthorizedNetworksRequest {
    /**
     * 
     * @type {Array<AuthorizedNetwork>}
     * @memberof UpdateAuthorizedNetworksRequest
     */
    'authorizedNetworks': Array<AuthorizedNetwork>;
}

