/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UsageAlert
 */
export interface UsageAlert {
    /**
     * 
     * @type {string}
     * @memberof UsageAlert
     */
    'type': UsageAlertTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UsageAlert
     */
    'message': string;
    /**
     * 
     * @type {number}
     * @memberof UsageAlert
     */
    'percentUsed': number;
}

export const UsageAlertTypeEnum = {
    Warning: 'warning',
    Critical: 'critical',
    Info: 'info'
} as const;

export type UsageAlertTypeEnum = typeof UsageAlertTypeEnum[keyof typeof UsageAlertTypeEnum];


