/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityTypeUSER } from './entity-type-user';
// May contain unused imports in some cases
// @ts-ignore
import { UserProjectRole } from './user-project-role';

/**
 * 
 * @export
 * @interface UserProjectResponse
 */
export interface UserProjectResponse {
    /**
     * 
     * @type {string}
     * @memberof UserProjectResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypeUSER}
     * @memberof UserProjectResponse
     */
    'object': EntityTypeUSER;
    /**
     * 
     * @type {number}
     * @memberof UserProjectResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {number}
     * @memberof UserProjectResponse
     */
    'updatedAt': number;
    /**
     * 
     * @type {string}
     * @memberof UserProjectResponse
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof UserProjectResponse
     */
    'lastName': string;
    /**
     * 
     * @type {UserProjectRole}
     * @memberof UserProjectResponse
     */
    'role': UserProjectRole;
    /**
     * 
     * @type {string}
     * @memberof UserProjectResponse
     */
    'email': string;
}



