/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PrismaSortOrder } from './prisma-sort-order';

/**
 * 
 * @export
 * @interface UserListQueries
 */
export interface UserListQueries {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof UserListQueries
     */
    'limit'?: number;
    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof UserListQueries
     */
    'skip'?: number;
    /**
     * 
     * @type {PrismaSortOrder}
     * @memberof UserListQueries
     */
    'order'?: PrismaSortOrder;
    /**
     * Filter by user name.
     * @type {string}
     * @memberof UserListQueries
     */
    'name'?: string;
    /**
     * Filter by external user ID (accountId from linked accounts).
     * @type {string}
     * @memberof UserListQueries
     */
    'externalUserId'?: string;
    /**
     * Filter by user email.
     * @type {string}
     * @memberof UserListQueries
     */
    'email'?: string;
    /**
     * Filter by user phone number.
     * @type {string}
     * @memberof UserListQueries
     */
    'phoneNumber'?: string;
    /**
     * Filter by provider ID (e.g., \"google\", \"apple\", \"siwe\", \"credential\").
     * @type {string}
     * @memberof UserListQueries
     */
    'authProviderId'?: string;
    /**
     * Filter by wallet client type (for SIWE accounts).
     * @type {string}
     * @memberof UserListQueries
     */
    'walletClientType'?: string;
}



