/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://openfort.xyz/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { EntityTypeWEB3CONNECTION } from './entity-type-web3-connection';
// May contain unused imports in some cases
// @ts-ignore
import { Web3ConnectionResponsePlayer } from './web3-connection-response-player';

/**
 * 
 * @export
 * @interface Web3ConnectionResponse
 */
export interface Web3ConnectionResponse {
    /**
     * 
     * @type {string}
     * @memberof Web3ConnectionResponse
     */
    'id': string;
    /**
     * 
     * @type {EntityTypeWEB3CONNECTION}
     * @memberof Web3ConnectionResponse
     */
    'object': EntityTypeWEB3CONNECTION;
    /**
     * 
     * @type {number}
     * @memberof Web3ConnectionResponse
     */
    'createdAt': number;
    /**
     * 
     * @type {boolean}
     * @memberof Web3ConnectionResponse
     */
    'disconnected': boolean;
    /**
     * 
     * @type {Web3ConnectionResponsePlayer}
     * @memberof Web3ConnectionResponse
     */
    'player': Web3ConnectionResponsePlayer;
}



