/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AssetTypeFilter } from '../models';
// @ts-ignore
import { WalletAssetsResponse } from '../models';
/**
 * AssetsApi - axios parameter creator
 * @export
 */
export const AssetsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Get wallet assets (native tokens and ERC20 tokens) across multiple chains.  This endpoint fetches token balances for a given wallet address across all supported chains or specific chains if filtered. It includes: - Native token balances (ETH, MATIC, etc.) - ERC20 token balances - USD pricing information (optional) - Token metadata (name, symbol, decimals)  Results are cached for 5 minutes to improve performance.  By default, fetches balances for popular stablecoins (USDC, USDT, DAI) and wrapped tokens on each chain. You can customize this using the `assetFilter` parameter.
         * @summary Get wallet assets across chains
         * @param {string} address The wallet address to query (EVM address format)
         * @param {Array<number>} [chainFilter] 
         * @param {string} [assetFilter] 
         * @param {Array<AssetTypeFilter>} [assetTypeFilter] 
         * @param {boolean} [includePrices] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssets: async (address: string, chainFilter?: Array<number>, assetFilter?: string, assetTypeFilter?: Array<AssetTypeFilter>, includePrices?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'address' is not null or undefined
            assertParamExists('getAssets', 'address', address)
            const localVarPath = `/v1/assets/{address}`
                .replace(`{${"address"}}`, encodeURIComponent(String(address)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (chainFilter) {
                localVarQueryParameter['chainFilter'] = chainFilter;
            }

            if (assetFilter !== undefined) {
                localVarQueryParameter['assetFilter'] = assetFilter;
            }

            if (assetTypeFilter) {
                localVarQueryParameter['assetTypeFilter'] = assetTypeFilter;
            }

            if (includePrices !== undefined) {
                localVarQueryParameter['includePrices'] = includePrices;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssetsApi - functional programming interface
 * @export
 */
export const AssetsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssetsApiAxiosParamCreator(configuration)
    return {
        /**
         * Get wallet assets (native tokens and ERC20 tokens) across multiple chains.  This endpoint fetches token balances for a given wallet address across all supported chains or specific chains if filtered. It includes: - Native token balances (ETH, MATIC, etc.) - ERC20 token balances - USD pricing information (optional) - Token metadata (name, symbol, decimals)  Results are cached for 5 minutes to improve performance.  By default, fetches balances for popular stablecoins (USDC, USDT, DAI) and wrapped tokens on each chain. You can customize this using the `assetFilter` parameter.
         * @summary Get wallet assets across chains
         * @param {string} address The wallet address to query (EVM address format)
         * @param {Array<number>} [chainFilter] 
         * @param {string} [assetFilter] 
         * @param {Array<AssetTypeFilter>} [assetTypeFilter] 
         * @param {boolean} [includePrices] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAssets(address: string, chainFilter?: Array<number>, assetFilter?: string, assetTypeFilter?: Array<AssetTypeFilter>, includePrices?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WalletAssetsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAssets(address, chainFilter, assetFilter, assetTypeFilter, includePrices, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * AssetsApi - factory interface
 * @export
 */
export const AssetsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssetsApiFp(configuration)
    return {
        /**
         * Get wallet assets (native tokens and ERC20 tokens) across multiple chains.  This endpoint fetches token balances for a given wallet address across all supported chains or specific chains if filtered. It includes: - Native token balances (ETH, MATIC, etc.) - ERC20 token balances - USD pricing information (optional) - Token metadata (name, symbol, decimals)  Results are cached for 5 minutes to improve performance.  By default, fetches balances for popular stablecoins (USDC, USDT, DAI) and wrapped tokens on each chain. You can customize this using the `assetFilter` parameter.
         * @summary Get wallet assets across chains
         * @param {AssetsApiGetAssetsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssets(requestParameters: AssetsApiGetAssetsRequest, options?: AxiosRequestConfig): AxiosPromise<WalletAssetsResponse> {
            return localVarFp.getAssets(requestParameters.address, requestParameters.chainFilter, requestParameters.assetFilter, requestParameters.assetTypeFilter, requestParameters.includePrices, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAssets operation in AssetsApi.
 * @export
 * @interface AssetsApiGetAssetsRequest
 */
export interface AssetsApiGetAssetsRequest {
    /**
     * The wallet address to query (EVM address format)
     * @type {string}
     * @memberof AssetsApiGetAssets
     */
    readonly address: string

    /**
     * 
     * @type {Array<number>}
     * @memberof AssetsApiGetAssets
     */
    readonly chainFilter?: Array<number>

    /**
     * 
     * @type {string}
     * @memberof AssetsApiGetAssets
     */
    readonly assetFilter?: string

    /**
     * 
     * @type {Array<AssetTypeFilter>}
     * @memberof AssetsApiGetAssets
     */
    readonly assetTypeFilter?: Array<AssetTypeFilter>

    /**
     * 
     * @type {boolean}
     * @memberof AssetsApiGetAssets
     */
    readonly includePrices?: boolean
}

/**
 * AssetsApi - object-oriented interface
 * @export
 * @class AssetsApi
 * @extends {BaseAPI}
 */
export class AssetsApi extends BaseAPI {
    /**
     * Get wallet assets (native tokens and ERC20 tokens) across multiple chains.  This endpoint fetches token balances for a given wallet address across all supported chains or specific chains if filtered. It includes: - Native token balances (ETH, MATIC, etc.) - ERC20 token balances - USD pricing information (optional) - Token metadata (name, symbol, decimals)  Results are cached for 5 minutes to improve performance.  By default, fetches balances for popular stablecoins (USDC, USDT, DAI) and wrapped tokens on each chain. You can customize this using the `assetFilter` parameter.
     * @summary Get wallet assets across chains
     * @param {AssetsApiGetAssetsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssetsApi
     */
    public getAssets(requestParameters: AssetsApiGetAssetsRequest, options?: AxiosRequestConfig) {
        return AssetsApiFp(this.configuration).getAssets(requestParameters.address, requestParameters.chainFilter, requestParameters.assetFilter, requestParameters.assetTypeFilter, requestParameters.includePrices, options).then((request) => request(this.axios, this.basePath));
    }
}

