/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ProjectLogs } from '../models';
/**
 * LogsApi - axios parameter creator
 * @export
 */
export const LogsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get logs for a project.
         * @param {Array<string>} [method] .
         * @param {string} [id] Specifies the unique project ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectLogs: async (method?: Array<string>, id?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/logs`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (method) {
                localVarQueryParameter['method'] = method;
            }

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get webhook logs for a project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWebhookLogsByProjectId: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/logs/webhook`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LogsApi - functional programming interface
 * @export
 */
export const LogsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LogsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get logs for a project.
         * @param {Array<string>} [method] .
         * @param {string} [id] Specifies the unique project ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectLogs(method?: Array<string>, id?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectLogs>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectLogs(method, id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get webhook logs for a project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWebhookLogsByProjectId(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProjectLogs>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWebhookLogsByProjectId(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * LogsApi - factory interface
 * @export
 */
export const LogsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LogsApiFp(configuration)
    return {
        /**
         * 
         * @summary Get logs for a project.
         * @param {LogsApiGetProjectLogsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectLogs(requestParameters: LogsApiGetProjectLogsRequest = {}, options?: AxiosRequestConfig): AxiosPromise<ProjectLogs> {
            return localVarFp.getProjectLogs(requestParameters.method, requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get webhook logs for a project.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWebhookLogsByProjectId(options?: AxiosRequestConfig): AxiosPromise<ProjectLogs> {
            return localVarFp.getWebhookLogsByProjectId(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getProjectLogs operation in LogsApi.
 * @export
 * @interface LogsApiGetProjectLogsRequest
 */
export interface LogsApiGetProjectLogsRequest {
    /**
     * .
     * @type {Array<string>}
     * @memberof LogsApiGetProjectLogs
     */
    readonly method?: Array<string>

    /**
     * Specifies the unique project ID.
     * @type {string}
     * @memberof LogsApiGetProjectLogs
     */
    readonly id?: string
}

/**
 * LogsApi - object-oriented interface
 * @export
 * @class LogsApi
 * @extends {BaseAPI}
 */
export class LogsApi extends BaseAPI {
    /**
     * 
     * @summary Get logs for a project.
     * @param {LogsApiGetProjectLogsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public getProjectLogs(requestParameters: LogsApiGetProjectLogsRequest = {}, options?: AxiosRequestConfig) {
        return LogsApiFp(this.configuration).getProjectLogs(requestParameters.method, requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get webhook logs for a project.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LogsApi
     */
    public getWebhookLogsByProjectId(options?: AxiosRequestConfig) {
        return LogsApiFp(this.configuration).getWebhookLogsByProjectId(options).then((request) => request(this.axios, this.basePath));
    }
}

