/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { JsonRpcRequest } from '../models';
// @ts-ignore
import { JsonRpcResponse } from '../models';
/**
 * RPCApi - axios parameter creator
 * @export
 */
export const RPCApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Handle JSON-RPC 2.0 requests  Accepts standard JSON-RPC 2.0 requests and routes them to appropriate method handlers.  Supported methods: - wallet_getAssets: Get wallet assets across multiple chains
         * @summary Execute JSON-RPC method
         * @param {JsonRpcRequest} jsonRpcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleRpcRequest: async (jsonRpcRequest: JsonRpcRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jsonRpcRequest' is not null or undefined
            assertParamExists('handleRpcRequest', 'jsonRpcRequest', jsonRpcRequest)
            const localVarPath = `/rpc`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jsonRpcRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RPCApi - functional programming interface
 * @export
 */
export const RPCApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RPCApiAxiosParamCreator(configuration)
    return {
        /**
         * Handle JSON-RPC 2.0 requests  Accepts standard JSON-RPC 2.0 requests and routes them to appropriate method handlers.  Supported methods: - wallet_getAssets: Get wallet assets across multiple chains
         * @summary Execute JSON-RPC method
         * @param {JsonRpcRequest} jsonRpcRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async handleRpcRequest(jsonRpcRequest: JsonRpcRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<JsonRpcResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.handleRpcRequest(jsonRpcRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RPCApi - factory interface
 * @export
 */
export const RPCApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RPCApiFp(configuration)
    return {
        /**
         * Handle JSON-RPC 2.0 requests  Accepts standard JSON-RPC 2.0 requests and routes them to appropriate method handlers.  Supported methods: - wallet_getAssets: Get wallet assets across multiple chains
         * @summary Execute JSON-RPC method
         * @param {RPCApiHandleRpcRequestRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        handleRpcRequest(requestParameters: RPCApiHandleRpcRequestRequest, options?: AxiosRequestConfig): AxiosPromise<JsonRpcResponse> {
            return localVarFp.handleRpcRequest(requestParameters.jsonRpcRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for handleRpcRequest operation in RPCApi.
 * @export
 * @interface RPCApiHandleRpcRequestRequest
 */
export interface RPCApiHandleRpcRequestRequest {
    /**
     * 
     * @type {JsonRpcRequest}
     * @memberof RPCApiHandleRpcRequest
     */
    readonly jsonRpcRequest: JsonRpcRequest
}

/**
 * RPCApi - object-oriented interface
 * @export
 * @class RPCApi
 * @extends {BaseAPI}
 */
export class RPCApi extends BaseAPI {
    /**
     * Handle JSON-RPC 2.0 requests  Accepts standard JSON-RPC 2.0 requests and routes them to appropriate method handlers.  Supported methods: - wallet_getAssets: Get wallet assets across multiple chains
     * @summary Execute JSON-RPC method
     * @param {RPCApiHandleRpcRequestRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RPCApi
     */
    public handleRpcRequest(requestParameters: RPCApiHandleRpcRequestRequest, options?: AxiosRequestConfig) {
        return RPCApiFp(this.configuration).handleRpcRequest(requestParameters.jsonRpcRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

