/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { SiweNoncePost200Response } from '../models';
// @ts-ignore
import { SiweNoncePostRequest } from '../models';
// @ts-ignore
import { SiweVerifyPost200Response } from '../models';
// @ts-ignore
import { SiweVerifyPost401Response } from '../models';
// @ts-ignore
import { SiweVerifyPostRequest } from '../models';
// @ts-ignore
import { SocialSignIn400Response } from '../models';
// @ts-ignore
import { SocialSignIn403Response } from '../models';
/**
 * SIWEApi - axios parameter creator
 * @export
 */
export const SIWEApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generate a nonce for Sign-In With Ethereum (SIWE) authentication
         * @param {SiweNoncePostRequest} siweNoncePostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siweNoncePost: async (siweNoncePostRequest: SiweNoncePostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'siweNoncePostRequest' is not null or undefined
            assertParamExists('siweNoncePost', 'siweNoncePostRequest', siweNoncePostRequest)
            const localVarPath = `/siwe/nonce`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(siweNoncePostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Verify a signed SIWE message and authenticate the user
         * @param {SiweVerifyPostRequest} siweVerifyPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siweVerifyPost: async (siweVerifyPostRequest: SiweVerifyPostRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'siweVerifyPostRequest' is not null or undefined
            assertParamExists('siweVerifyPost', 'siweVerifyPostRequest', siweVerifyPostRequest)
            const localVarPath = `/siwe/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(siweVerifyPostRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SIWEApi - functional programming interface
 * @export
 */
export const SIWEApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SIWEApiAxiosParamCreator(configuration)
    return {
        /**
         * Generate a nonce for Sign-In With Ethereum (SIWE) authentication
         * @param {SiweNoncePostRequest} siweNoncePostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async siweNoncePost(siweNoncePostRequest: SiweNoncePostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SiweNoncePost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.siweNoncePost(siweNoncePostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Verify a signed SIWE message and authenticate the user
         * @param {SiweVerifyPostRequest} siweVerifyPostRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async siweVerifyPost(siweVerifyPostRequest: SiweVerifyPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SiweVerifyPost200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.siweVerifyPost(siweVerifyPostRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SIWEApi - factory interface
 * @export
 */
export const SIWEApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SIWEApiFp(configuration)
    return {
        /**
         * Generate a nonce for Sign-In With Ethereum (SIWE) authentication
         * @param {SIWEApiSiweNoncePostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siweNoncePost(requestParameters: SIWEApiSiweNoncePostRequest, options?: AxiosRequestConfig): AxiosPromise<SiweNoncePost200Response> {
            return localVarFp.siweNoncePost(requestParameters.siweNoncePostRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Verify a signed SIWE message and authenticate the user
         * @param {SIWEApiSiweVerifyPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        siweVerifyPost(requestParameters: SIWEApiSiweVerifyPostRequest, options?: AxiosRequestConfig): AxiosPromise<SiweVerifyPost200Response> {
            return localVarFp.siweVerifyPost(requestParameters.siweVerifyPostRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for siweNoncePost operation in SIWEApi.
 * @export
 * @interface SIWEApiSiweNoncePostRequest
 */
export interface SIWEApiSiweNoncePostRequest {
    /**
     * 
     * @type {SiweNoncePostRequest}
     * @memberof SIWEApiSiweNoncePost
     */
    readonly siweNoncePostRequest: SiweNoncePostRequest
}

/**
 * Request parameters for siweVerifyPost operation in SIWEApi.
 * @export
 * @interface SIWEApiSiweVerifyPostRequest
 */
export interface SIWEApiSiweVerifyPostRequest {
    /**
     * 
     * @type {SiweVerifyPostRequest}
     * @memberof SIWEApiSiweVerifyPost
     */
    readonly siweVerifyPostRequest: SiweVerifyPostRequest
}

/**
 * SIWEApi - object-oriented interface
 * @export
 * @class SIWEApi
 * @extends {BaseAPI}
 */
export class SIWEApi extends BaseAPI {
    /**
     * Generate a nonce for Sign-In With Ethereum (SIWE) authentication
     * @param {SIWEApiSiweNoncePostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SIWEApi
     */
    public siweNoncePost(requestParameters: SIWEApiSiweNoncePostRequest, options?: AxiosRequestConfig) {
        return SIWEApiFp(this.configuration).siweNoncePost(requestParameters.siweNoncePostRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Verify a signed SIWE message and authenticate the user
     * @param {SIWEApiSiweVerifyPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SIWEApi
     */
    public siweVerifyPost(requestParameters: SIWEApiSiweVerifyPostRequest, options?: AxiosRequestConfig) {
        return SIWEApiFp(this.configuration).siweVerifyPost(requestParameters.siweVerifyPostRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

