/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateTransactionRequestV2 } from '../models';
// @ts-ignore
import { EstimateTransactionResponseV2 } from '../models';
// @ts-ignore
import { InvalidRequestErrorResponse } from '../models';
// @ts-ignore
import { PrismaSortOrder } from '../models';
// @ts-ignore
import { SubmitTransactionSignatureRequestV2 } from '../models';
// @ts-ignore
import { TransactionExpandableV2 } from '../models';
// @ts-ignore
import { TransactionListResponseV2 } from '../models';
// @ts-ignore
import { TransactionResponseV2 } from '../models';
// @ts-ignore
import { TransactionStatusV2 } from '../models';
/**
 * TransactionsApi - axios parameter creator
 * @export
 */
export const TransactionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a transaction for an account.  For accounts whose key is held by the user, the response has `status: \"awaiting_signature\"` and a `nextAction` with the hash to sign; submit the signature with `POST /v2/transactions/{id}/signature`. For custodial and backend-wallet accounts the transaction is signed and broadcast in the same call and the response already carries a `receipt` (unless `waitForReceipt` is `false`).
         * @summary Create a transaction.
         * @param {CreateTransactionRequestV2} createTransactionRequestV2 
         * @param {string} [xBehalfOfProject] Project ID to act on behalf of (for ecosystem operations).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransactionV2: async (createTransactionRequestV2: CreateTransactionRequestV2, xBehalfOfProject?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTransactionRequestV2' is not null or undefined
            assertParamExists('createTransactionV2', 'createTransactionRequestV2', createTransactionRequestV2)
            const localVarPath = `/v2/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication pk_third_party required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication auth_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication pk_access_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (xBehalfOfProject != null) {
                localVarHeaderParameter['X-Behalf-Of-Project'] = String(xBehalfOfProject);
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionRequestV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Estimates the gas cost of a transaction without sending it.  With a fee sponsorship that charges the user in an ERC-20 token, `feeInToken` is the estimated amount of that token.
         * @summary Estimate a transaction\'s gas cost.
         * @param {CreateTransactionRequestV2} createTransactionRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        estimateTransactionV2: async (createTransactionRequestV2: CreateTransactionRequestV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createTransactionRequestV2' is not null or undefined
            assertParamExists('estimateTransactionV2', 'createTransactionRequestV2', createTransactionRequestV2)
            const localVarPath = `/v2/transactions/estimate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication pk_third_party required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication auth_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication pk_access_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createTransactionRequestV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves a transaction. Poll this endpoint until `status` is terminal (`succeeded`, `reverted` or `failed`).
         * @summary Get a transaction.
         * @param {string} id The transaction ID (starts with tin_).
         * @param {Array<TransactionExpandableV2>} [expand] Specifies the expandable fields.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionV2: async (id: string, expand?: Array<TransactionExpandableV2>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTransactionV2', 'id', id)
            const localVarPath = `/v2/transactions/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication pk_third_party required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication user_project required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication auth_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication pk_access_token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (expand) {
                localVarQueryParameter['expand'] = expand;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a list of transactions, most recent first.
         * @summary List transactions.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {Array<TransactionExpandableV2>} [expand] Specifies the fields to expand in the response. &#x60;timeline&#x60; adds the lifecycle history (one monitor lookup per request); &#x60;userOperation&#x60; and &#x60;logs&#x60; add the heavyweight execution payload and receipt logs, which are otherwise omitted.
         * @param {number} [chainId] The chain ID. Must be a [supported chain](/development/chains).
         * @param {Array<string>} [accountId] Filter by account ID (starts with acc_).
         * @param {Array<string>} [userId] Filter by user ID (starts with usr_).
         * @param {Array<string>} [walletId] Filter by wallet ID (starts with pla_).
         * @param {Array<string>} [feeSponsorshipId] Filter by fee sponsorship ID (starts with pol_).
         * @param {TransactionStatusV2} [status] Filter by transaction status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactionsV2: async (limit?: number, skip?: number, order?: PrismaSortOrder, expand?: Array<TransactionExpandableV2>, chainId?: number, accountId?: Array<string>, userId?: Array<string>, walletId?: Array<string>, feeSponsorshipId?: Array<string>, status?: TransactionStatusV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication user_project required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (expand) {
                localVarQueryParameter['expand'] = expand;
            }

            if (chainId !== undefined) {
                localVarQueryParameter['chainId'] = chainId;
            }

            if (accountId) {
                localVarQueryParameter['accountId'] = accountId;
            }

            if (userId) {
                localVarQueryParameter['userId'] = userId;
            }

            if (walletId) {
                localVarQueryParameter['walletId'] = walletId;
            }

            if (feeSponsorshipId) {
                localVarQueryParameter['feeSponsorshipId'] = feeSponsorshipId;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Submits the signature of `nextAction.hash` and broadcasts the transaction.
         * @summary Submit a transaction signature.
         * @param {string} id The transaction ID (starts with tin_).
         * @param {SubmitTransactionSignatureRequestV2} submitTransactionSignatureRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTransactionSignatureV2: async (id: string, submitTransactionSignatureRequestV2: SubmitTransactionSignatureRequestV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submitTransactionSignatureV2', 'id', id)
            // verify required parameter 'submitTransactionSignatureRequestV2' is not null or undefined
            assertParamExists('submitTransactionSignatureV2', 'submitTransactionSignatureRequestV2', submitTransactionSignatureRequestV2)
            const localVarPath = `/v2/transactions/{id}/signature`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication pk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitTransactionSignatureRequestV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransactionsApi - functional programming interface
 * @export
 */
export const TransactionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransactionsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a transaction for an account.  For accounts whose key is held by the user, the response has `status: \"awaiting_signature\"` and a `nextAction` with the hash to sign; submit the signature with `POST /v2/transactions/{id}/signature`. For custodial and backend-wallet accounts the transaction is signed and broadcast in the same call and the response already carries a `receipt` (unless `waitForReceipt` is `false`).
         * @summary Create a transaction.
         * @param {CreateTransactionRequestV2} createTransactionRequestV2 
         * @param {string} [xBehalfOfProject] Project ID to act on behalf of (for ecosystem operations).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createTransactionV2(createTransactionRequestV2: CreateTransactionRequestV2, xBehalfOfProject?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionResponseV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTransactionV2(createTransactionRequestV2, xBehalfOfProject, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Estimates the gas cost of a transaction without sending it.  With a fee sponsorship that charges the user in an ERC-20 token, `feeInToken` is the estimated amount of that token.
         * @summary Estimate a transaction\'s gas cost.
         * @param {CreateTransactionRequestV2} createTransactionRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async estimateTransactionV2(createTransactionRequestV2: CreateTransactionRequestV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EstimateTransactionResponseV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.estimateTransactionV2(createTransactionRequestV2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves a transaction. Poll this endpoint until `status` is terminal (`succeeded`, `reverted` or `failed`).
         * @summary Get a transaction.
         * @param {string} id The transaction ID (starts with tin_).
         * @param {Array<TransactionExpandableV2>} [expand] Specifies the expandable fields.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTransactionV2(id: string, expand?: Array<TransactionExpandableV2>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionResponseV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransactionV2(id, expand, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Returns a list of transactions, most recent first.
         * @summary List transactions.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {Array<TransactionExpandableV2>} [expand] Specifies the fields to expand in the response. &#x60;timeline&#x60; adds the lifecycle history (one monitor lookup per request); &#x60;userOperation&#x60; and &#x60;logs&#x60; add the heavyweight execution payload and receipt logs, which are otherwise omitted.
         * @param {number} [chainId] The chain ID. Must be a [supported chain](/development/chains).
         * @param {Array<string>} [accountId] Filter by account ID (starts with acc_).
         * @param {Array<string>} [userId] Filter by user ID (starts with usr_).
         * @param {Array<string>} [walletId] Filter by wallet ID (starts with pla_).
         * @param {Array<string>} [feeSponsorshipId] Filter by fee sponsorship ID (starts with pol_).
         * @param {TransactionStatusV2} [status] Filter by transaction status.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listTransactionsV2(limit?: number, skip?: number, order?: PrismaSortOrder, expand?: Array<TransactionExpandableV2>, chainId?: number, accountId?: Array<string>, userId?: Array<string>, walletId?: Array<string>, feeSponsorshipId?: Array<string>, status?: TransactionStatusV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionListResponseV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTransactionsV2(limit, skip, order, expand, chainId, accountId, userId, walletId, feeSponsorshipId, status, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Submits the signature of `nextAction.hash` and broadcasts the transaction.
         * @summary Submit a transaction signature.
         * @param {string} id The transaction ID (starts with tin_).
         * @param {SubmitTransactionSignatureRequestV2} submitTransactionSignatureRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitTransactionSignatureV2(id: string, submitTransactionSignatureRequestV2: SubmitTransactionSignatureRequestV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransactionResponseV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitTransactionSignatureV2(id, submitTransactionSignatureRequestV2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TransactionsApi - factory interface
 * @export
 */
export const TransactionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransactionsApiFp(configuration)
    return {
        /**
         * Creates a transaction for an account.  For accounts whose key is held by the user, the response has `status: \"awaiting_signature\"` and a `nextAction` with the hash to sign; submit the signature with `POST /v2/transactions/{id}/signature`. For custodial and backend-wallet accounts the transaction is signed and broadcast in the same call and the response already carries a `receipt` (unless `waitForReceipt` is `false`).
         * @summary Create a transaction.
         * @param {TransactionsApiCreateTransactionV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createTransactionV2(requestParameters: TransactionsApiCreateTransactionV2Request, options?: AxiosRequestConfig): AxiosPromise<TransactionResponseV2> {
            return localVarFp.createTransactionV2(requestParameters.createTransactionRequestV2, requestParameters.xBehalfOfProject, options).then((request) => request(axios, basePath));
        },
        /**
         * Estimates the gas cost of a transaction without sending it.  With a fee sponsorship that charges the user in an ERC-20 token, `feeInToken` is the estimated amount of that token.
         * @summary Estimate a transaction\'s gas cost.
         * @param {TransactionsApiEstimateTransactionV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        estimateTransactionV2(requestParameters: TransactionsApiEstimateTransactionV2Request, options?: AxiosRequestConfig): AxiosPromise<EstimateTransactionResponseV2> {
            return localVarFp.estimateTransactionV2(requestParameters.createTransactionRequestV2, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves a transaction. Poll this endpoint until `status` is terminal (`succeeded`, `reverted` or `failed`).
         * @summary Get a transaction.
         * @param {TransactionsApiGetTransactionV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTransactionV2(requestParameters: TransactionsApiGetTransactionV2Request, options?: AxiosRequestConfig): AxiosPromise<TransactionResponseV2> {
            return localVarFp.getTransactionV2(requestParameters.id, requestParameters.expand, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a list of transactions, most recent first.
         * @summary List transactions.
         * @param {TransactionsApiListTransactionsV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listTransactionsV2(requestParameters: TransactionsApiListTransactionsV2Request = {}, options?: AxiosRequestConfig): AxiosPromise<TransactionListResponseV2> {
            return localVarFp.listTransactionsV2(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.expand, requestParameters.chainId, requestParameters.accountId, requestParameters.userId, requestParameters.walletId, requestParameters.feeSponsorshipId, requestParameters.status, options).then((request) => request(axios, basePath));
        },
        /**
         * Submits the signature of `nextAction.hash` and broadcasts the transaction.
         * @summary Submit a transaction signature.
         * @param {TransactionsApiSubmitTransactionSignatureV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitTransactionSignatureV2(requestParameters: TransactionsApiSubmitTransactionSignatureV2Request, options?: AxiosRequestConfig): AxiosPromise<TransactionResponseV2> {
            return localVarFp.submitTransactionSignatureV2(requestParameters.id, requestParameters.submitTransactionSignatureRequestV2, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTransactionV2 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiCreateTransactionV2Request
 */
export interface TransactionsApiCreateTransactionV2Request {
    /**
     * 
     * @type {CreateTransactionRequestV2}
     * @memberof TransactionsApiCreateTransactionV2
     */
    readonly createTransactionRequestV2: CreateTransactionRequestV2

    /**
     * Project ID to act on behalf of (for ecosystem operations).
     * @type {string}
     * @memberof TransactionsApiCreateTransactionV2
     */
    readonly xBehalfOfProject?: string
}

/**
 * Request parameters for estimateTransactionV2 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiEstimateTransactionV2Request
 */
export interface TransactionsApiEstimateTransactionV2Request {
    /**
     * 
     * @type {CreateTransactionRequestV2}
     * @memberof TransactionsApiEstimateTransactionV2
     */
    readonly createTransactionRequestV2: CreateTransactionRequestV2
}

/**
 * Request parameters for getTransactionV2 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiGetTransactionV2Request
 */
export interface TransactionsApiGetTransactionV2Request {
    /**
     * The transaction ID (starts with tin_).
     * @type {string}
     * @memberof TransactionsApiGetTransactionV2
     */
    readonly id: string

    /**
     * Specifies the expandable fields.
     * @type {Array<TransactionExpandableV2>}
     * @memberof TransactionsApiGetTransactionV2
     */
    readonly expand?: Array<TransactionExpandableV2>
}

/**
 * Request parameters for listTransactionsV2 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiListTransactionsV2Request
 */
export interface TransactionsApiListTransactionsV2Request {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly limit?: number

    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly skip?: number

    /**
     * Specifies the order in which to sort the results.
     * @type {PrismaSortOrder}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly order?: PrismaSortOrder

    /**
     * Specifies the fields to expand in the response. &#x60;timeline&#x60; adds the lifecycle history (one monitor lookup per request); &#x60;userOperation&#x60; and &#x60;logs&#x60; add the heavyweight execution payload and receipt logs, which are otherwise omitted.
     * @type {Array<TransactionExpandableV2>}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly expand?: Array<TransactionExpandableV2>

    /**
     * The chain ID. Must be a [supported chain](/development/chains).
     * @type {number}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly chainId?: number

    /**
     * Filter by account ID (starts with acc_).
     * @type {Array<string>}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly accountId?: Array<string>

    /**
     * Filter by user ID (starts with usr_).
     * @type {Array<string>}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly userId?: Array<string>

    /**
     * Filter by wallet ID (starts with pla_).
     * @type {Array<string>}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly walletId?: Array<string>

    /**
     * Filter by fee sponsorship ID (starts with pol_).
     * @type {Array<string>}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly feeSponsorshipId?: Array<string>

    /**
     * Filter by transaction status.
     * @type {TransactionStatusV2}
     * @memberof TransactionsApiListTransactionsV2
     */
    readonly status?: TransactionStatusV2
}

/**
 * Request parameters for submitTransactionSignatureV2 operation in TransactionsApi.
 * @export
 * @interface TransactionsApiSubmitTransactionSignatureV2Request
 */
export interface TransactionsApiSubmitTransactionSignatureV2Request {
    /**
     * The transaction ID (starts with tin_).
     * @type {string}
     * @memberof TransactionsApiSubmitTransactionSignatureV2
     */
    readonly id: string

    /**
     * 
     * @type {SubmitTransactionSignatureRequestV2}
     * @memberof TransactionsApiSubmitTransactionSignatureV2
     */
    readonly submitTransactionSignatureRequestV2: SubmitTransactionSignatureRequestV2
}

/**
 * TransactionsApi - object-oriented interface
 * @export
 * @class TransactionsApi
 * @extends {BaseAPI}
 */
export class TransactionsApi extends BaseAPI {
    /**
     * Creates a transaction for an account.  For accounts whose key is held by the user, the response has `status: \"awaiting_signature\"` and a `nextAction` with the hash to sign; submit the signature with `POST /v2/transactions/{id}/signature`. For custodial and backend-wallet accounts the transaction is signed and broadcast in the same call and the response already carries a `receipt` (unless `waitForReceipt` is `false`).
     * @summary Create a transaction.
     * @param {TransactionsApiCreateTransactionV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public createTransactionV2(requestParameters: TransactionsApiCreateTransactionV2Request, options?: AxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).createTransactionV2(requestParameters.createTransactionRequestV2, requestParameters.xBehalfOfProject, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Estimates the gas cost of a transaction without sending it.  With a fee sponsorship that charges the user in an ERC-20 token, `feeInToken` is the estimated amount of that token.
     * @summary Estimate a transaction\'s gas cost.
     * @param {TransactionsApiEstimateTransactionV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public estimateTransactionV2(requestParameters: TransactionsApiEstimateTransactionV2Request, options?: AxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).estimateTransactionV2(requestParameters.createTransactionRequestV2, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves a transaction. Poll this endpoint until `status` is terminal (`succeeded`, `reverted` or `failed`).
     * @summary Get a transaction.
     * @param {TransactionsApiGetTransactionV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public getTransactionV2(requestParameters: TransactionsApiGetTransactionV2Request, options?: AxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).getTransactionV2(requestParameters.id, requestParameters.expand, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a list of transactions, most recent first.
     * @summary List transactions.
     * @param {TransactionsApiListTransactionsV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public listTransactionsV2(requestParameters: TransactionsApiListTransactionsV2Request = {}, options?: AxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).listTransactionsV2(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.expand, requestParameters.chainId, requestParameters.accountId, requestParameters.userId, requestParameters.walletId, requestParameters.feeSponsorshipId, requestParameters.status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Submits the signature of `nextAction.hash` and broadcasts the transaction.
     * @summary Submit a transaction signature.
     * @param {TransactionsApiSubmitTransactionSignatureV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TransactionsApi
     */
    public submitTransactionSignatureV2(requestParameters: TransactionsApiSubmitTransactionSignatureV2Request, options?: AxiosRequestConfig) {
        return TransactionsApiFp(this.configuration).submitTransactionSignatureV2(requestParameters.id, requestParameters.submitTransactionSignatureRequestV2, options).then((request) => request(this.axios, this.basePath));
    }
}

