/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AuthUserResponse } from '../models';
// @ts-ignore
import { BaseEntityListResponseAuthUserResponse } from '../models';
// @ts-ignore
import { PrismaSortOrder } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUser: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAuthUser', 'id', id)
            const localVarPath = `/v2/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: { ...baseOptions, ...localVarRequestOptions},
            };
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {string} [name] Filter by user name.
         * @param {string} [externalUserId] Filter by external user ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUsers: async (limit?: number, skip?: number, order?: PrismaSortOrder, name?: string, externalUserId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (externalUserId !== undefined) {
                localVarQueryParameter['externalUserId'] = externalUserId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthUser(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {string} [name] Filter by user name.
         * @param {string} [externalUserId] Filter by external user ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthUsers(limit?: number, skip?: number, order?: PrismaSortOrder, name?: string, externalUserId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseEntityListResponseAuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthUsers(limit, skip, order, name, externalUserId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {UsersApiGetAuthUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUser(requestParameters: UsersApiGetAuthUserRequest, options?: AxiosRequestConfig): AxiosPromise<AuthUserResponse> {
            return localVarFp.getAuthUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary Authenticated user.
         * @param {UsersApiGetAuthUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUsers(requestParameters: UsersApiGetAuthUsersRequest = {}, options?: AxiosRequestConfig): AxiosPromise<BaseEntityListResponseAuthUserResponse> {
            return localVarFp.getAuthUsers(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.name, requestParameters.externalUserId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAuthUser operation in UsersApi.
 * @export
 * @interface UsersApiGetAuthUserRequest
 */
export interface UsersApiGetAuthUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersApiGetAuthUser
     */
    readonly id: string
}

/**
 * Request parameters for getAuthUsers operation in UsersApi.
 * @export
 * @interface UsersApiGetAuthUsersRequest
 */
export interface UsersApiGetAuthUsersRequest {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof UsersApiGetAuthUsers
     */
    readonly limit?: number

    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof UsersApiGetAuthUsers
     */
    readonly skip?: number

    /**
     * Specifies the order in which to sort the results.
     * @type {PrismaSortOrder}
     * @memberof UsersApiGetAuthUsers
     */
    readonly order?: PrismaSortOrder

    /**
     * Filter by user name.
     * @type {string}
     * @memberof UsersApiGetAuthUsers
     */
    readonly name?: string

    /**
     * Filter by external user ID.
     * @type {string}
     * @memberof UsersApiGetAuthUsers
     */
    readonly externalUserId?: string
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
     * @summary Authenticated user.
     * @param {UsersApiGetAuthUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getAuthUser(requestParameters: UsersApiGetAuthUserRequest, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).getAuthUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
     * @summary Authenticated user.
     * @param {UsersApiGetAuthUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getAuthUsers(requestParameters: UsersApiGetAuthUsersRequest = {}, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).getAuthUsers(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.name, requestParameters.externalUserId, options).then((request) => request(this.axios, this.basePath));
    }
}

