/* tslint:disable */
/* eslint-disable */
/**
 * Openfort API
 * Complete Openfort API references and guides can be found at: https://www.openfort.io/docs
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: founders@openfort.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AuthUserResponse } from '../models';
// @ts-ignore
import { BaseDeleteEntityResponseEntityTypePLAYER } from '../models';
// @ts-ignore
import { BaseEntityListResponseAuthUserResponse } from '../models';
// @ts-ignore
import { PregenerateAccountResponse } from '../models';
// @ts-ignore
import { PregenerateUserRequestV2 } from '../models';
// @ts-ignore
import { PrismaSortOrder } from '../models';
// @ts-ignore
import { ThirdPartyOAuthRequest } from '../models';
/**
 * UsersApi - axios parameter creator
 * @export
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * It will delete all linked accounts the user is authenticated with. If the user has a linked embedded signer, it will be deleted as well.
         * @summary Delete user by id.
         * @param {string} id Specifies the unique user ID (starts with pla_).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteUser', 'id', id)
            const localVarPath = `/v2/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Get authenticated user by id.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUser: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAuthUser', 'id', id)
            const localVarPath = `/v2/users/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary List authenticated users.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {string} [name] Filter by user name.
         * @param {string} [externalUserId] Filter by external user ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUsers: async (limit?: number, skip?: number, order?: PrismaSortOrder, name?: string, externalUserId?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v2/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (externalUserId !== undefined) {
                localVarQueryParameter['externalUserId'] = externalUserId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meV2: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/iam/v2/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Pre-generate a user with an embedded account before they authenticate. Creates a user record and an embedded account using the provided SSS key shares. When the user later authenticates (via email, OAuth, third-party auth, etc.) with the same identifier, they will be linked to this pre-generated account.  You can pregenerate using either: - `email`: User will be linked when they authenticate with the same email - `thirdPartyUserId` + `thirdPartyProvider`: User will be linked when they authenticate via the same third-party provider
         * @summary Pre-generate a user with an embedded account.
         * @param {PregenerateUserRequestV2} pregenerateUserRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pregenerateUserV2: async (pregenerateUserRequestV2: PregenerateUserRequestV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'pregenerateUserRequestV2' is not null or undefined
            assertParamExists('pregenerateUserV2', 'pregenerateUserRequestV2', pregenerateUserRequestV2)
            const localVarPath = `/v2/users/pregenerate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(pregenerateUserRequestV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify oauth token of a third party auth provider.
         * @param {ThirdPartyOAuthRequest} thirdPartyOAuthRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        thirdPartyV2: async (thirdPartyOAuthRequest: ThirdPartyOAuthRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'thirdPartyOAuthRequest' is not null or undefined
            assertParamExists('thirdPartyV2', 'thirdPartyOAuthRequest', thirdPartyOAuthRequest)
            const localVarPath = `/iam/v2/user/third_party`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication pk required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(thirdPartyOAuthRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 * @export
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * It will delete all linked accounts the user is authenticated with. If the user has a linked embedded signer, it will be deleted as well.
         * @summary Delete user by id.
         * @param {string} id Specifies the unique user ID (starts with pla_).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseDeleteEntityResponseEntityTypePLAYER>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Get authenticated user by id.
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthUser(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthUser(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary List authenticated users.
         * @param {number} [limit] Specifies the maximum number of records to return.
         * @param {number} [skip] Specifies the offset for the first records to return.
         * @param {PrismaSortOrder} [order] Specifies the order in which to sort the results.
         * @param {string} [name] Filter by user name.
         * @param {string} [externalUserId] Filter by external user ID.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuthUsers(limit?: number, skip?: number, order?: PrismaSortOrder, name?: string, externalUserId?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseEntityListResponseAuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuthUsers(limit, skip, order, name, externalUserId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async meV2(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.meV2(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Pre-generate a user with an embedded account before they authenticate. Creates a user record and an embedded account using the provided SSS key shares. When the user later authenticates (via email, OAuth, third-party auth, etc.) with the same identifier, they will be linked to this pre-generated account.  You can pregenerate using either: - `email`: User will be linked when they authenticate with the same email - `thirdPartyUserId` + `thirdPartyProvider`: User will be linked when they authenticate via the same third-party provider
         * @summary Pre-generate a user with an embedded account.
         * @param {PregenerateUserRequestV2} pregenerateUserRequestV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async pregenerateUserV2(pregenerateUserRequestV2: PregenerateUserRequestV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PregenerateAccountResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.pregenerateUserV2(pregenerateUserRequestV2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Verify oauth token of a third party auth provider.
         * @param {ThirdPartyOAuthRequest} thirdPartyOAuthRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async thirdPartyV2(thirdPartyOAuthRequest: ThirdPartyOAuthRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthUserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.thirdPartyV2(thirdPartyOAuthRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UsersApi - factory interface
 * @export
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * It will delete all linked accounts the user is authenticated with. If the user has a linked embedded signer, it will be deleted as well.
         * @summary Delete user by id.
         * @param {UsersApiDeleteUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(requestParameters: UsersApiDeleteUserRequest, options?: AxiosRequestConfig): AxiosPromise<BaseDeleteEntityResponseEntityTypePLAYER> {
            return localVarFp.deleteUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
         * @summary Get authenticated user by id.
         * @param {UsersApiGetAuthUserRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUser(requestParameters: UsersApiGetAuthUserRequest, options?: AxiosRequestConfig): AxiosPromise<AuthUserResponse> {
            return localVarFp.getAuthUser(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
         * @summary List authenticated users.
         * @param {UsersApiGetAuthUsersRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuthUsers(requestParameters: UsersApiGetAuthUsersRequest = {}, options?: AxiosRequestConfig): AxiosPromise<BaseEntityListResponseAuthUserResponse> {
            return localVarFp.getAuthUsers(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.name, requestParameters.externalUserId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get user information.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        meV2(options?: AxiosRequestConfig): AxiosPromise<AuthUserResponse> {
            return localVarFp.meV2(options).then((request) => request(axios, basePath));
        },
        /**
         * Pre-generate a user with an embedded account before they authenticate. Creates a user record and an embedded account using the provided SSS key shares. When the user later authenticates (via email, OAuth, third-party auth, etc.) with the same identifier, they will be linked to this pre-generated account.  You can pregenerate using either: - `email`: User will be linked when they authenticate with the same email - `thirdPartyUserId` + `thirdPartyProvider`: User will be linked when they authenticate via the same third-party provider
         * @summary Pre-generate a user with an embedded account.
         * @param {UsersApiPregenerateUserV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        pregenerateUserV2(requestParameters: UsersApiPregenerateUserV2Request, options?: AxiosRequestConfig): AxiosPromise<PregenerateAccountResponse> {
            return localVarFp.pregenerateUserV2(requestParameters.pregenerateUserRequestV2, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify oauth token of a third party auth provider.
         * @param {UsersApiThirdPartyV2Request} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        thirdPartyV2(requestParameters: UsersApiThirdPartyV2Request, options?: AxiosRequestConfig): AxiosPromise<AuthUserResponse> {
            return localVarFp.thirdPartyV2(requestParameters.thirdPartyOAuthRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteUser operation in UsersApi.
 * @export
 * @interface UsersApiDeleteUserRequest
 */
export interface UsersApiDeleteUserRequest {
    /**
     * Specifies the unique user ID (starts with pla_).
     * @type {string}
     * @memberof UsersApiDeleteUser
     */
    readonly id: string
}

/**
 * Request parameters for getAuthUser operation in UsersApi.
 * @export
 * @interface UsersApiGetAuthUserRequest
 */
export interface UsersApiGetAuthUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UsersApiGetAuthUser
     */
    readonly id: string
}

/**
 * Request parameters for getAuthUsers operation in UsersApi.
 * @export
 * @interface UsersApiGetAuthUsersRequest
 */
export interface UsersApiGetAuthUsersRequest {
    /**
     * Specifies the maximum number of records to return.
     * @type {number}
     * @memberof UsersApiGetAuthUsers
     */
    readonly limit?: number

    /**
     * Specifies the offset for the first records to return.
     * @type {number}
     * @memberof UsersApiGetAuthUsers
     */
    readonly skip?: number

    /**
     * Specifies the order in which to sort the results.
     * @type {PrismaSortOrder}
     * @memberof UsersApiGetAuthUsers
     */
    readonly order?: PrismaSortOrder

    /**
     * Filter by user name.
     * @type {string}
     * @memberof UsersApiGetAuthUsers
     */
    readonly name?: string

    /**
     * Filter by external user ID.
     * @type {string}
     * @memberof UsersApiGetAuthUsers
     */
    readonly externalUserId?: string
}

/**
 * Request parameters for pregenerateUserV2 operation in UsersApi.
 * @export
 * @interface UsersApiPregenerateUserV2Request
 */
export interface UsersApiPregenerateUserV2Request {
    /**
     * 
     * @type {PregenerateUserRequestV2}
     * @memberof UsersApiPregenerateUserV2
     */
    readonly pregenerateUserRequestV2: PregenerateUserRequestV2
}

/**
 * Request parameters for thirdPartyV2 operation in UsersApi.
 * @export
 * @interface UsersApiThirdPartyV2Request
 */
export interface UsersApiThirdPartyV2Request {
    /**
     * 
     * @type {ThirdPartyOAuthRequest}
     * @memberof UsersApiThirdPartyV2
     */
    readonly thirdPartyOAuthRequest: ThirdPartyOAuthRequest
}

/**
 * UsersApi - object-oriented interface
 * @export
 * @class UsersApi
 * @extends {BaseAPI}
 */
export class UsersApi extends BaseAPI {
    /**
     * It will delete all linked accounts the user is authenticated with. If the user has a linked embedded signer, it will be deleted as well.
     * @summary Delete user by id.
     * @param {UsersApiDeleteUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public deleteUser(requestParameters: UsersApiDeleteUserRequest, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).deleteUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves an authenticated user.  Users have linked accounts and are authenticated with a provider.
     * @summary Get authenticated user by id.
     * @param {UsersApiGetAuthUserRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getAuthUser(requestParameters: UsersApiGetAuthUserRequest, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).getAuthUser(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves an authenticated users.  Users have linked accounts and are authenticated with a provider.
     * @summary List authenticated users.
     * @param {UsersApiGetAuthUsersRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public getAuthUsers(requestParameters: UsersApiGetAuthUsersRequest = {}, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).getAuthUsers(requestParameters.limit, requestParameters.skip, requestParameters.order, requestParameters.name, requestParameters.externalUserId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get user information.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public meV2(options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).meV2(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Pre-generate a user with an embedded account before they authenticate. Creates a user record and an embedded account using the provided SSS key shares. When the user later authenticates (via email, OAuth, third-party auth, etc.) with the same identifier, they will be linked to this pre-generated account.  You can pregenerate using either: - `email`: User will be linked when they authenticate with the same email - `thirdPartyUserId` + `thirdPartyProvider`: User will be linked when they authenticate via the same third-party provider
     * @summary Pre-generate a user with an embedded account.
     * @param {UsersApiPregenerateUserV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public pregenerateUserV2(requestParameters: UsersApiPregenerateUserV2Request, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).pregenerateUserV2(requestParameters.pregenerateUserRequestV2, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify oauth token of a third party auth provider.
     * @param {UsersApiThirdPartyV2Request} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UsersApi
     */
    public thirdPartyV2(requestParameters: UsersApiThirdPartyV2Request, options?: AxiosRequestConfig) {
        return UsersApiFp(this.configuration).thirdPartyV2(requestParameters.thirdPartyOAuthRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

