name: Upload Static

on:
  release:
    types: [created]
  # push:
  #   branches: main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.16.1

      - name: Setup Node
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build JS Bundler
        run: pnpm build:platform-bridge

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          credentials_json: '${{ secrets.GCP_BUCKET_SA_KEY }}'

      - name: Upload to GCP Bucket
        uses: google-github-actions/upload-cloud-storage@7c6e11cb7291594c5dfe0bc1dd9cd905e31e600c # v2.2.2
        with:
          path: 'packages/platform-bridge/dist/bundle/index.js'
          destination: 'static-openfort-xyz/js/${{github.event.release.tag_name}}'
