name: Run pnpm build
on:
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pnpm-build:
    name: pnpm build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    env:
      NODE_OPTIONS: --max-old-space-size=14366
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.4.0

      - name: Set up Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 24
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Security audit
        run: pnpm audit
      
      - name: sherif
        run: pnpm check:repo

      - name: Code check (Biome)
        run: pnpm biome check

      # - name: Check TypeScript types
      #   run: pnpm check:types

      - name: Check for unused files, dependencies, and exports
        run: pnpm knip --production

      - name: Build project
        run: pnpm build

      - name: Verify package exports
        run: pnpm test:build
